import { useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpenText, ClipboardText, Books, ChartLineUp, CheckCircle, CaretRight, Eye, Trophy, PaperPlaneTilt, WarningCircle } from '@phosphor-icons/react/ssr';

// The original screens share this presentation between demo and school data.

export function StudentAssignmentView({assignment,existing,answer,onChange,onSubmit,feedback='',error='',busy=false,connected=false,ui:{RouteLink,PageHeader,DemoBadge}}){
  const submitted=Boolean(existing),reviewed=existing?.status==='Corrigé';
  return <><nav className="detail-breadcrumb" aria-label="Fil d’Ariane"><RouteLink to="/eleve/devoirs"><ArrowLeft/> Retour à mes devoirs</RouteLink></nav><PageHeader eyebrow="MON DEVOIR" title={assignment.title} subtitle={`${assignment.subject||"Français"} · à rendre le ${new Date(assignment.dueAt).toLocaleDateString("fr-FR")}`} serif action={<span className={`status-pill ${reviewed?"success":"warning"}`}>{reviewed?`Corrigé · ${existing.score}/20`:submitted?"Remis · correction en attente":"À faire"}</span>}/>{feedback&&<div className="editor-success" role="status"><CheckCircle weight="fill"/><span><strong>Remise enregistrée</strong><small>{feedback}</small></span></div>}{reviewed&&<div className="assignment-feedback" role="status"><Trophy weight="duotone"/><div><span>{connected?"RETOUR DE TON ENSEIGNANT":"CORRECTION DE MME BENJELLOUN"}</span><h2>{existing.score}/20</h2><p>{existing.feedback}</p></div></div>}<div className="assignment-detail-layout"><form className="panel assignment-response" onSubmit={onSubmit}><span className="eyebrow">Consigne</span><h2>{assignment.instructions}</h2><label htmlFor="student-assignment-answer">Ma réponse</label><textarea id="student-assignment-answer" minLength={connected?12:undefined} maxLength={connected?6000:undefined} required={connected} value={answer} onChange={event=>onChange(event.target.value)} placeholder="Écris ta réponse ici…" readOnly={reviewed||(connected&&(submitted||busy))} aria-describedby="student-answer-help student-answer-error"/><small id="student-answer-help">{connected?"De 12 à 6 000 caractères · Après remise, le travail est conservé sur ton compte et ne peut plus être remplacé.":"Minimum 12 caractères · Ta réponse reste enregistrée sur cet appareil."}</small>{error&&<p className="form-error" id="student-answer-error" role="alert"><WarningCircle/>{error}</p>}<button className="button button-dark" type="submit" disabled={busy||reviewed||(connected&&submitted)}><PaperPlaneTilt/>{busy?"Enregistrement…":connected&&submitted?"Travail remis":submitted?"Mettre à jour ma remise":"Envoyer ma remise"}</button></form><aside className="panel assignment-guide"><ClipboardText weight="duotone"/><h2>Avant d’envoyer</h2><ol><li>Relis la consigne.</li><li>{connected?"Vérifie tes phrases.":"Vérifie les cinq adjectifs."}</li><li>Corrige les accords simples.</li></ol><div className="prototype-note">{!connected&&<DemoBadge/>}<p>{connected?"Le travail est envoyé à ton enseignant seulement après confirmation du serveur.":"Cette remise est fictive et stockée uniquement dans ce navigateur."}</p></div></aside></div></>;
}
// No demo store, identity fallback or implicit business data belongs here.
export function StudentDashboardView({currentUser,active=null,latest=null,todo=[],pendingCount,classLabel='Mon école',connected=false,ui:{PageHeader,RouteLink,ResponsiveImage}}){
  const latestLabel=latest?.experienceType==="market-tier"?"Palier terminé":latest?.experienceType==="guided-mission"?"Mission terminée":latest?.experienceType==="learning-activity"?"Activité corrigée":latest?.quizId==="mots-fleches"?"Grille terminée":latest?"Entraînement terminé":"Commence une activité";
  return <>
    <PageHeader eyebrow={connected?"MON ESPACE ÉLÈVE":"MON ESPACE DE DÉMONSTRATION"} title={`Bonjour ${currentUser?.name?.split(" ")[0]||"à toi"}`} subtitle="Lis, essaie, puis prends le temps de comprendre la correction." action={<RouteLink to={connected?"/pilote/jeux/mots-fleches":"/eleve/activites/mots-environnement"} className="button button-gold">M’entraîner <ArrowRight/></RouteLink>}/>
    <section className="student-journey"><div><span>JE PRATIQUE · {active?.level||(connected?classLabel:"5e AEP")}</span><h2>{connected?"Des mots à découvrir":"Les mots de l’environnement"}</h2><p>{connected?"Retrouve tes mots fléchés et reprends les grilles enregistrées sur ton compte.":"Cinq questions pour comprendre et réutiliser le vocabulaire. Une explication t’aide après chaque réponse."}</p><p>Les jeux et les XP ne valident pas automatiquement une unité du manuel.</p></div><ResponsiveImage fileName="generated-1774018865796.png" alt="Livre illustré" sizes="230px"/></section>
    <div className="dashboard-two-columns"><article className="panel assignment-panel"><div className="panel-top"><span className="status-pill warning">{pendingCount ?? todo.length} à faire</span><small>Prochaine échéance</small></div><h3>{todo[0]?.title||"Aucun devoir à remettre"}</h3><p>{todo[0]?`Pour le ${new Date(todo[0].dueAt).toLocaleDateString("fr-FR")}`:"Retrouve les retours disponibles dans Mes devoirs."}</p>{todo[0]&&<RouteLink to={`/eleve/devoirs/${todo[0].id}`} className="button button-light">Ouvrir le devoir <ArrowRight/></RouteLink>}</article><article className="streak-card"><small>DERNIÈRE ACTIVITÉ</small><strong>{latest?`${latest.correctCount}/${latest.questionCount}`:"À toi !"}</strong><b>{latestLabel}</b><span>{latest?`${latest.xpEarned||0} XP attribués · ${latest.experienceType==="guided-mission"?"étapes réussies au premier essai":latest.experienceType==="market-tier"?"missions réussies, avec ou sans aide":"résultat de cette activité"}`:"Un résultat expliqué, à ton rythme"}</span></article></div>
    <div className="quick-grid"><RouteLink to="/eleve/manuels"><BookOpenText/><strong>Mes manuels</strong><span>{active?.manualTitle||"Découvrir le manuel"}</span></RouteLink><RouteLink to="/eleve/devoirs"><ClipboardText/><strong>Mes devoirs</strong><span>{pendingCount ?? todo.length} à faire</span></RouteLink><RouteLink to="/eleve/mediatheque"><Books/><strong>Médiathèque</strong><span>Audio, vidéo et livres</span></RouteLink><RouteLink to="/eleve/progression"><ChartLineUp/><strong>Mes résultats</strong><span>Activités et entraînements</span></RouteLink></div>
  </>;
}

export function StudentHomeworkView({homework=[],counts,connected=false,ui:{PageHeader,RouteLink,Tabs}}){
  const [tab,setTab]=useState("afaire");
  const [correction,setCorrection]=useState("");
  const todo=homework.filter(item=>item.status==="À faire");
  const completed=homework.filter(item=>item.status!=="À faire");
  const items=tab==="afaire"?todo:completed;
  return <><PageHeader eyebrow={connected?"MON TRAVAIL":"MON TRAVAIL · DÉMONSTRATION LOCALE"} title="Mes devoirs" subtitle={connected?"Retrouve les devoirs de ta classe et les retours enregistrés sur ton compte.":"Retrouve les devoirs de ta classe et les retours enregistrés sur cet appareil."}/><Tabs value={tab} onChange={value=>{setTab(value);setCorrection("")}} items={[["afaire",`À faire · ${counts?.pending ?? todo.length}`],["termines",`Remis · ${counts?.submitted ?? completed.length}`]]}/>{correction&&<div className="editor-success" role="status"><CheckCircle/><span><strong>Retour enregistré</strong><small>{correction}</small></span></div>}<div className="list-panel">{items.length?items.map(item=><article className="homework-row" key={item.id}><span className="row-icon"><ClipboardText/></span><div><h3>{item.title}</h3><p>{item.subject||"Français"} · pour le {new Date(item.dueAt).toLocaleDateString("fr-FR")}</p></div><span className={item.status==="Corrigé"?"status-pill success":"status-pill warning"}>{item.status}{item.status==="Corrigé"?` · ${item.submission.score}/20`:""}</span>{item.status==="À faire"||connected?<RouteLink className="icon-button" to={`/eleve/devoirs/${item.id}`} aria-label={item.status==="À faire"?`Ouvrir ${item.title}`:`Lire ma copie et le suivi de ${item.title}`}>{item.status==="À faire"?<CaretRight/>:<Eye/>}</RouteLink>:<button className="icon-button" aria-label={`Consulter le suivi de ${item.title}`} onClick={()=>setCorrection(item.status==="Corrigé"?item.submission.feedback:connected?"Ton travail est enregistré sur ton compte. Aucune correction n’est encore disponible.":"La remise est enregistrée localement. Aucune correction n’est encore disponible.")}><Eye/></button>}</article>):<p className="popover-empty">{connected&&counts?.nextOffset!=null?'Aucun devoir dans cette sélection parmi les éléments chargés. Charge la suite ci-dessous.':'Aucun devoir dans cette liste.'}</p>}</div></>;
}
