import test from 'node:test';
import assert from 'node:assert/strict';
import { GameSync, gameCacheKey } from '../src/features/pilote/gameSync.js';
import { MOTS_FLECHES_GRIDS } from '../src/features/games/mots-fleches/motsFlechesData.js';
import { buildGridModel } from '../src/features/games/mots-fleches/motsFlechesEngine.js';
const gridId=MOTS_FLECHES_GRIDS[0].id;
const key=[...buildGridModel(MOTS_FLECHES_GRIDS[0]).cells.entries()].find(([,cell])=>cell.type==='letter')[0];
function setup({send,storage,initial}={}) {
  const cache=new Map();storage ||= {getItem:k=>cache.get(k),setItem:(k,v)=>cache.set(k,v)};
  let revision=0;const calls=[];
  const client=new GameSync({userId:'student-a',schoolId:'school-a',storage,initial:initial||{userId:'student-a',schoolId:'school-a',xpTotal:0,grids:[]},send:async(id,action,body)=>{calls.push({id,action,body});return send?send(id,action,body):{userId:'student-a',schoolId:'school-a',xpTotal:action==='complete'?20:0,awarded:action==='complete',grid:{gridId:id,progress:body.progress,hintCount:body.hintCount,revision:++revision,lastRequestId:body.requestId,completedAt:action==='complete'?1:null,awardedXp:action==='complete'?20:0}};}});
  const update=(letter='E')=>client.update({...client.snapshot().progressByGrid,[gridId]:{[key]:letter}},{});
  return {client,cache,storage,calls,update};
}
test('le chargement sans modification ne crée aucune écriture',async()=>{const h=setup();const s=h.client.snapshot();h.client.update(s.progressByGrid,s.hintCounts);assert.equal(await h.client.flush(),true);assert.equal(h.calls.length,0);});
test('les modifications rapides sont regroupées et sauvegardées par identité',async()=>{const h=setup();h.update('E');h.update('C');await h.client.flush();assert.equal(h.calls.length,1);assert.equal(h.calls[0].body.progress[key],'C');assert.equal(h.calls[0].body.ownerId,'student-a');assert.equal(h.client.snapshot().pending,0);});
test('une réponse réseau perdue réutilise exactement la même requête',async()=>{let fail=true;const h=setup({send:async(id,action,body)=>{if(fail)throw new Error('offline');return {userId:'student-a',schoolId:'school-a',xpTotal:0,grid:{gridId:id,...body,revision:1,lastRequestId:body.requestId}};}});h.update();assert.equal(await h.client.flush(),false);fail=false;await h.client.flush();assert.deepEqual(h.calls[1].body,h.calls[0].body);assert.equal(h.client.snapshot().pending,0);});
test('la saisie pendant un envoi utilise la prochaine révision',async()=>{let resolve;const gate=new Promise(r=>{resolve=r;});const h=setup({send:async(id,action,body)=>{if(body.revision===0)await gate;return {userId:'student-a',schoolId:'school-a',xpTotal:0,grid:{gridId:id,...body,revision:body.revision+1,lastRequestId:body.requestId}};}});h.update('E');const pending=h.client.flush();h.update('C');resolve();await pending;assert.equal(h.calls.length,2);assert.equal(h.calls[1].body.revision,1);assert.notEqual(h.calls[1].body.requestId,h.calls[0].body.requestId);});
test('une autre identité ne reçoit ni copie locale ni progression',()=>{const h=setup();h.update();const second=new GameSync({userId:'student-b',schoolId:'school-a',initial:{userId:'student-b',schoolId:'school-a',xpTotal:0,grids:[]},storage:h.storage,send:()=>{}});assert.equal(second.snapshot().pending,0);assert.equal(second.snapshot().progressByGrid[gridId][key],'');assert.notEqual(gameCacheKey('student-a','school-a'),gameCacheKey('student-a','school-b'));});
test('une réponse appartenant à un autre compte ne valide pas la sauvegarde',async()=>{const h=setup({send:async()=>({userId:'student-b',schoolId:'school-a',xpTotal:500})});h.update();assert.equal(await h.client.flush(),false);assert.equal(h.client.snapshot().error.status,401);assert.equal(h.client.snapshot().xpTotal,0);});
test('un conflit conserve le brouillon et exige un choix explicite',async()=>{let conflict=true;const remote={gridId,progress:{[key]:'A'},revision:3,hintCount:0};const h=setup({send:async(id,action,body)=>{if(conflict)throw Object.assign(new Error('conflict'),{status:409,data:{grid:remote}});return {userId:'student-a',schoolId:'school-a',xpTotal:0,grid:{...remote,progress:body.progress,revision:4}};}});h.update();await h.client.flush();assert.equal(h.client.snapshot().conflicts.length,1);assert.equal(await h.client.flush(),false);assert.equal(h.calls.length,1);h.client.resolveConflicts(true);conflict=false;await h.client.flush();assert.equal(h.calls[1].body.revision,3);assert.equal(h.calls[1].body.progress[key],'E');});
test('reprendre la version serveur abandonne seulement le brouillon choisi',async()=>{const remote={gridId,progress:{[key]:'A'},revision:3,hintCount:0};const h=setup({send:async()=>{throw Object.assign(new Error('conflict'),{status:409,data:{grid:remote}});}});h.update();await h.client.flush();h.client.resolveConflicts(false);assert.equal(h.client.snapshot().pending,0);assert.equal(h.client.snapshot().progressByGrid[gridId][key],'A');});
test('un rechargement détecte une autre version sans écraser le compte',()=>{const h=setup();h.update();const next=setup({storage:h.storage,initial:{userId:'student-a',schoolId:'school-a',xpTotal:0,grids:[{gridId,progress:{[key]:'A'},hintCount:0,revision:2}]}});assert.deepEqual(next.client.snapshot().conflicts,[gridId]);assert.equal(next.client.snapshot().progressByGrid[gridId][key],'E');});
test('le stockage inaccessible ne bloque pas le jeu mais est signalé',async()=>{const h=setup({storage:{getItem(){throw Error();},setItem(){throw Error();}}});h.update();assert.equal(h.client.snapshot().storageWarning,true);assert.equal(await h.client.flush(),true);});
test('une grille terminée attend la confirmation serveur des XP',async()=>{let resolve;const gate=new Promise(r=>{resolve=r;});const h=setup({send:async(id,action,body)=>{await gate;return {userId:'student-a',schoolId:'school-a',xpTotal:20,awarded:true,grid:{gridId:id,...body,revision:1,completedAt:1,awardedXp:20}};}});const pending=h.client.complete(gridId,{[key]:'E'},0);assert.equal(h.client.snapshot().xpTotal,0);resolve();assert.deepEqual(await pending,{ok:true,awarded:true,totalXp:20});});
test('un composant quitté ignore une réponse tardive',async()=>{let resolve;const gate=new Promise(r=>{resolve=r;});const h=setup({send:async()=>{await gate;return {userId:'student-a',schoolId:'school-a',xpTotal:999,grid:{gridId,revision:1}};}});h.update();const pending=h.client.flush();h.client.dispose();resolve();assert.equal(await pending,false);assert.equal(h.client.snapshot().xpTotal,0);});
test('le choix de la copie du compte actualise aussi les XP du conflit',async()=>{const remote={gridId,progress:{[key]:'A'},revision:3,hintCount:0,completedAt:1,awardedXp:20};const h=setup({send:async()=>{throw Object.assign(new Error('conflict'),{status:409,data:{userId:'student-a',schoolId:'school-a',xpTotal:20,grid:remote}});}});h.update();await h.client.flush();h.client.resolveConflicts(false);assert.equal(h.client.snapshot().xpTotal,20);assert.equal(h.client.snapshot().pending,0);});
test('la sauvegarde suivante ne masque pas la récompense de la grille terminée',async()=>{let release;const gate=new Promise(r=>{release=r;});const second=MOTS_FLECHES_GRIDS[1].id;const h=setup({send:async(id,action,body)=>{if(id===gridId)await gate;return {userId:'student-a',schoolId:'school-a',xpTotal:20,awarded:action==='complete',grid:{gridId:id,...body,revision:1,completedAt:action==='complete'?1:null}};}});const completed=h.client.complete(gridId,{[key]:'E'},0);const state=h.client.snapshot();h.client.update({...state.progressByGrid,[second]:{...state.progressByGrid[second],[Object.keys(state.progressByGrid[second])[0]]:'A'}},state.hintCounts);release();assert.equal((await completed).awarded,true);assert.equal(h.calls.length,2);});
