import { QUESTION_STATUSES } from "./questionBankConstants.js";

const question = (value) => Object.freeze({
  ...value,
  choices: Object.freeze([...value.choices]),
  tags: Object.freeze([...(value.tags || [])]),
  media: value.media ? Object.freeze({ ...value.media }) : null,
});

export const seedQuestionBank = Object.freeze([
  question({
    id: "qb-maroc-atlantique",
    category: "Culture marocaine",
    level: "5e AEP",
    difficulty: "facile",
    prompt: "Quel océan borde la côte ouest du Maroc ?",
    choices: ["La mer Méditerranée", "L’océan Atlantique", "L’océan Indien", "L’océan Pacifique"],
    correctIndex: 1,
    explanation: "L’océan Atlantique borde toute la côte ouest du Maroc, de Tanger à Lagouira.",
    status: QUESTION_STATUSES.PUBLISHED,
    tags: ["maroc", "géographie"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-maroc-capitale",
    category: "Culture marocaine",
    level: "4e AEP",
    difficulty: "facile",
    prompt: "Quelle ville est la capitale administrative du Maroc ?",
    choices: ["Casablanca", "Marrakech", "Rabat", "Fès"],
    correctIndex: 2,
    explanation: "Rabat est la capitale administrative du Maroc ; Casablanca en est la plus grande ville.",
    status: QUESTION_STATUSES.PUBLISHED,
    tags: ["maroc", "villes"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-maroc-atlas",
    category: "Culture marocaine",
    level: "6e AEP",
    difficulty: "intermediaire",
    prompt: "Quel est le plus haut sommet du Maroc et d’Afrique du Nord ?",
    choices: ["Le M’Goun", "Le Toubkal", "Le Siroua", "Le Tidighine"],
    correctIndex: 1,
    explanation: "Le Toubkal culmine à 4 167 mètres dans le Haut Atlas, au sud de Marrakech.",
    status: QUESTION_STATUSES.APPROVED,
    tags: ["maroc", "relief"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-langue-pluriel-journal",
    category: "Langue française",
    level: "4e AEP",
    difficulty: "facile",
    prompt: "Quel est le pluriel correct du mot « journal » ?",
    choices: ["Des journals", "Des journaux", "Des journales", "Des journails"],
    correctIndex: 1,
    explanation: "Le nom « journal » forme son pluriel en -aux : un journal, des journaux.",
    status: QUESTION_STATUSES.PUBLISHED,
    tags: ["grammaire", "pluriel"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-langue-accord-marche",
    category: "Langue française",
    level: "5e AEP",
    difficulty: "intermediaire",
    prompt: "Quelle phrase est correctement accordée ?",
    choices: ["Les marchandes sont installé.", "Les marchandes sont installées.", "Les marchande sont installés.", "Les marchandes est installée."],
    correctIndex: 1,
    explanation: "Le sujet « les marchandes » est féminin pluriel : on écrit « sont installées ».",
    status: QUESTION_STATUSES.APPROVED,
    tags: ["grammaire", "accord"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-langue-synonyme-joyeux",
    category: "Langue française",
    level: "3e AEP",
    difficulty: "facile",
    prompt: "Quel mot est un synonyme de « joyeux » ?",
    choices: ["Heureux", "Fatigué", "Silencieux", "Lointain"],
    correctIndex: 0,
    explanation: "« Heureux » et « joyeux » expriment tous les deux un sentiment de joie.",
    status: QUESTION_STATUSES.PUBLISHED,
    tags: ["vocabulaire", "synonymes"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-sciences-eau",
    category: "Sciences",
    level: "4e AEP",
    difficulty: "facile",
    prompt: "À quelle température l’eau pure gèle-t-elle normalement ?",
    choices: ["0 °C", "10 °C", "50 °C", "100 °C"],
    correctIndex: 0,
    explanation: "À pression normale, l’eau pure passe de l’état liquide à l’état solide à 0 °C.",
    status: QUESTION_STATUSES.PUBLISHED,
    tags: ["eau", "états de la matière"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-sciences-plante",
    category: "Sciences",
    level: "3e AEP",
    difficulty: "facile",
    prompt: "De quoi une plante verte a-t-elle besoin pour bien grandir ?",
    choices: ["D’eau et de lumière", "De sable seulement", "De sucre", "D’obscurité permanente"],
    correctIndex: 0,
    explanation: "Une plante verte a notamment besoin d’eau, de lumière, d’air et de sels minéraux.",
    status: QUESTION_STATUSES.APPROVED,
    tags: ["vivant", "plantes"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-sciences-planete",
    category: "Sciences",
    level: "5e AEP",
    difficulty: "intermediaire",
    prompt: "Quelle planète est la plus proche du Soleil ?",
    choices: ["Vénus", "La Terre", "Mars", "Mercure"],
    correctIndex: 3,
    explanation: "Mercure est la première planète du Système solaire et la plus proche du Soleil.",
    status: QUESTION_STATUSES.DRAFT,
    tags: ["espace", "système solaire"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-geographie-detroit",
    category: "Géographie",
    level: "6e AEP",
    difficulty: "intermediaire",
    prompt: "Quel détroit sépare le Maroc de l’Espagne ?",
    choices: ["Le détroit de Gibraltar", "Le détroit du Bosphore", "Le canal de Suez", "Le détroit de Béring"],
    correctIndex: 0,
    explanation: "Le détroit de Gibraltar relie l’Atlantique à la Méditerranée et sépare le Maroc de l’Espagne.",
    status: QUESTION_STATUSES.PUBLISHED,
    tags: ["maroc", "méditerranée"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-geographie-continent",
    category: "Géographie",
    level: "3e AEP",
    difficulty: "facile",
    prompt: "Sur quel continent se trouve le Maroc ?",
    choices: ["L’Europe", "L’Afrique", "L’Asie", "L’Amérique"],
    correctIndex: 1,
    explanation: "Le Maroc se trouve au nord-ouest du continent africain.",
    status: QUESTION_STATUSES.PUBLISHED,
    tags: ["maroc", "continents"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-histoire-verte",
    category: "Histoire",
    level: "6e AEP",
    difficulty: "intermediaire",
    prompt: "En quelle année la Marche verte a-t-elle eu lieu ?",
    choices: ["1956", "1963", "1975", "1999"],
    correctIndex: 2,
    explanation: "La Marche verte a eu lieu en 1975 ; elle constitue un événement majeur de l’histoire contemporaine du Maroc.",
    status: QUESTION_STATUSES.APPROVED,
    tags: ["maroc", "histoire contemporaine"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-histoire-imprimerie",
    category: "Histoire",
    level: "6e AEP",
    difficulty: "difficile",
    prompt: "Quel inventeur européen est associé à l’imprimerie à caractères mobiles au XVe siècle ?",
    choices: ["Louis Pasteur", "Johannes Gutenberg", "Galilée", "Thomas Edison"],
    correctIndex: 1,
    explanation: "Johannes Gutenberg a perfectionné en Europe l’impression à caractères mobiles au XVe siècle.",
    status: QUESTION_STATUSES.DRAFT,
    tags: ["inventions", "livre"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-francophonie-senegal",
    category: "Monde francophone",
    level: "5e AEP",
    difficulty: "intermediaire",
    prompt: "Quelle ville est la capitale du Sénégal ?",
    choices: ["Dakar", "Bamako", "Tunis", "Abidjan"],
    correctIndex: 0,
    explanation: "Dakar est la capitale du Sénégal, un pays francophone situé sur la côte atlantique de l’Afrique.",
    status: QUESTION_STATUSES.PUBLISHED,
    tags: ["francophonie", "afrique"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-francophonie-quebec",
    category: "Monde francophone",
    level: "6e AEP",
    difficulty: "intermediaire",
    prompt: "Dans quel pays se trouve la province francophone du Québec ?",
    choices: ["La Belgique", "Le Canada", "La Suisse", "La France"],
    correctIndex: 1,
    explanation: "Le Québec est une province du Canada où le français est la langue officielle.",
    status: QUESTION_STATUSES.APPROVED,
    tags: ["francophonie", "canada"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-arts-petit-prince",
    category: "Arts et littérature",
    level: "5e AEP",
    difficulty: "intermediaire",
    prompt: "Qui a écrit le récit « Le Petit Prince » ?",
    choices: ["Victor Hugo", "Antoine de Saint-Exupéry", "Jules Verne", "Molière"],
    correctIndex: 1,
    explanation: "Antoine de Saint-Exupéry a écrit et illustré « Le Petit Prince », publié en 1943.",
    status: QUESTION_STATUSES.PUBLISHED,
    tags: ["littérature", "auteur"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-arts-zellige",
    category: "Arts et littérature",
    level: "4e AEP",
    difficulty: "facile",
    prompt: "Comment appelle-t-on l’art décoratif marocain composé de petits carreaux colorés ?",
    choices: ["Le vitrail", "Le zellige", "La mosaïque romaine", "La fresque"],
    correctIndex: 1,
    explanation: "Le zellige assemble des morceaux de carreaux taillés pour former des motifs géométriques colorés.",
    status: QUESTION_STATUSES.PUBLISHED,
    tags: ["maroc", "patrimoine", "arts"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-vie-marche",
    category: "Vie quotidienne",
    level: "2e AEP",
    difficulty: "facile",
    prompt: "Quelle formule utilise-t-on pour demander poliment un prix au marché ?",
    choices: ["Donne-moi ça !", "Combien ça coûte, s’il vous plaît ?", "Je veux partir.", "Il fait beau aujourd’hui."],
    correctIndex: 1,
    explanation: "« Combien ça coûte, s’il vous plaît ? » permet de demander un prix avec politesse.",
    status: QUESTION_STATUSES.APPROVED,
    tags: ["oral", "politesse", "marché"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-vie-itineraire",
    category: "Vie quotidienne",
    level: "4e AEP",
    difficulty: "intermediaire",
    prompt: "Quelle consigne aide une personne à continuer dans la même direction ?",
    choices: ["Tournez à gauche.", "Faites demi-tour.", "Continuez tout droit.", "Arrêtez-vous ici."],
    correctIndex: 2,
    explanation: "« Continuez tout droit » indique qu’il faut avancer sans changer de direction.",
    status: QUESTION_STATUSES.DRAFT,
    tags: ["oral", "itinéraire"],
    source: "Jet d’Encre Éditions",
  }),
  question({
    id: "qb-langue-connecteur",
    category: "Langue française",
    level: "6e AEP",
    difficulty: "difficile",
    prompt: "Quel connecteur convient pour introduire une conséquence ?",
    choices: ["Parce que", "Pourtant", "Donc", "D’abord"],
    correctIndex: 2,
    explanation: "Le connecteur « donc » introduit une conséquence : il pleut, donc je prends mon parapluie.",
    status: QUESTION_STATUSES.APPROVED,
    tags: ["écriture", "connecteurs"],
    source: "Jet d’Encre Éditions",
  }),
]);

export default seedQuestionBank;
