import { useEffect, useRef, useState } from 'react';
import { Buildings, Plus, ShieldCheck, SignOut, Users } from '@phosphor-icons/react/ssr';
import './access-admin.css';

const roles={enseignant:'Enseignant',eleve:'Élève',parent:'Parent'};
const actions={school_created:'École créée',class_created:'Classe créée',account_created:'Compte préparé',identity_linked:'Connexion rattachée',school_suspended:'École suspendue',school_activated:'École réactivée',account_suspended:'Compte suspendu',account_activated:'Compte réactivé',sessions_revoked:'Sessions fermées'};
async function api(path,body,csrf){
  const response=await fetch('/api/pilot'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf||'', 'X-Local-Pilot':'1'},...(body===undefined?{}:{body:JSON.stringify(body)})});
  const data=await response.json();if(!response.ok){const error=new Error(data.error?.message||'Le service est indisponible.');error.status=response.status;throw error;}return data;
}
export default function AccessAdmin(){
  const [session,setSession]=useState(null),[data,setData]=useState(null),[schoolId,setSchoolId]=useState(''),[query,setQuery]=useState('');
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState(null),[draft,setDraft]=useState({});
  const epoch=useRef(0),identity=useRef(null);
  async function refresh(){const version=++epoch.current;try{const s=await api('/session');if(version!==epoch.current)return;if(identity.current!==s.user?.id){setForm(null);setDraft({});setSchoolId('');}identity.current=s.user?.id;setSession(s);if(!s.authenticated||s.user.role!=='admin'){setData(null);return;}const next=await api('/admin');if(version!==epoch.current)return;if(next.userId!==s.user.id)throw new Error('Le compte a changé. Actualisez la page.');setData(next);setSchoolId(previous=>previous||next.schools[0]?.id||'');}catch(e){if(version===epoch.current){setData(null);setError(e.message);}}}
  useEffect(()=>{refresh();const reset=()=>{setData(null);refresh();};window.addEventListener('focus',reset);return()=>{epoch.current++;window.removeEventListener('focus',reset);};},[]);
  async function mutate(path,body){setBusy(true);setError('');setNotice('');try{await api(path,body,session?.csrfToken);setForm(null);setNotice('Modification enregistrée.');await refresh();}catch(e){setError(e.message);if(e.status===401||e.status===403){setData(null);await refresh();}}finally{setBusy(false);}}
  function open(kind,account=null){setError('');setNotice('');setDraft({id:account?.id||crypto.randomUUID(),name:'',role:'enseignant',classId:'',childId:'',subject:'',schoolId});setForm(kind);}
  const school=data?.schools.find(s=>s.id===schoolId),accounts=data?.accounts.filter(a=>a.schoolId===schoolId)||[];
  const classes=data?.classes.filter(c=>c.schoolId===schoolId)||[];
  async function logout(){await mutate('/logout',{});setData(null);setSession(null);await refresh();}
  return <div className="access-admin"><header className="access-top"><a href="/">Jet d’Encre</a><span><ShieldCheck/> Administration</span>{session?.authenticated&&<button onClick={logout} disabled={busy}><SignOut/> Se déconnecter</button>}</header>
    <main><div className="access-heading"><div><span>GESTION DES ÉTABLISSEMENTS</span><h1>Écoles et accès</h1><p>Vous décidez qui peut se connecter et à quelle école.</p></div>{data&&<button className="access-primary" disabled={busy} onClick={()=>open('school')}><Plus/> Ajouter une école</button>}</div>
    {error&&<p className="access-error" role="alert">{error} <button onClick={refresh}>Actualiser</button></p>}{notice&&<p className="access-notice" role="status">{notice}</p>}
    {!session&&!error&&<p role="status">Vérification de votre accès…</p>}
    {session&&!session.authenticated&&<section className="access-panel"><h2>Connexion administrateur</h2><p>Utilisez votre compte administrateur attribué par Jet d’Encre.</p>{session.mode==='local_fixture'?<><p>Prévisualisation locale · écoles et comptes fictifs.</p><button className="access-primary" onClick={()=>mutate('/local/login',{profileId:'pilot-local-admin'})} disabled={busy}>Ouvrir l’administration de test</button></>:<a className="access-primary" href="/api/pilot/auth/start">Me connecter</a>}</section>}
    {session?.authenticated&&session.user.role!=='admin'&&<section className="access-panel"><h2>Accès réservé</h2><p>Ce compte ne dispose pas des droits d’administration Jet d’Encre.</p><a href="/pilote">Retour à mon espace</a></section>}
    {data&&<>{session.mode==='local_fixture'&&<p className="access-notice">Environnement local de test · aucune modification du site en ligne.</p>}<div className="access-layout"><aside className="access-panel"><h2><Buildings/> Établissements <small>{data.schools.length}</small></h2><label>Rechercher une école<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom de l’école"/></label><div className="access-schools">{data.schools.filter(s=>s.name.toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr'))).map(s=>{const accountCount=data.accounts.filter(a=>a.schoolId===s.id).length;return <button key={s.id} aria-pressed={schoolId===s.id} onClick={()=>{setSchoolId(s.id);setForm(null);}}><strong>{s.name}</strong><span>{s.active?'Active':'Suspendue'} · {accountCount} {accountCount===1?'compte':'comptes'}</span></button>;})}</div></aside>
    <section className="access-panel">{school?<><div className="access-school-title"><div><h2>{school.name}</h2><span className={school.active?'access-tag':'access-tag suspended'}>{school.active?'Accès ouverts':'École suspendue'}</span></div><button disabled={busy} onClick={()=>{if(window.confirm(school.active?'Suspendre cette école et fermer les sessions de ses utilisateurs ?':'Réactiver les accès de cette école ?'))mutate('/admin/school-status',{id:school.id,active:!school.active});}}>{school.active?'Suspendre l’école':'Réactiver l’école'}</button></div>
    <div className="access-toolbar"><h3><Users/> {accounts.length} {accounts.length===1?'compte':'comptes'}</h3><button disabled={busy||!school.active} onClick={()=>open('class')}>Ajouter une classe</button><button className="access-primary" disabled={busy||!school.active} onClick={()=>open('account')}><Plus/> Ajouter un compte</button></div>
    {!accounts.length?<p>Aucun compte pour cette école. Ajoutez une classe, puis les enseignants et les élèves. Vous pourrez ensuite rattacher leurs parents.</p>:<div className="access-table"><table><thead><tr><th>Utilisateur</th><th>Accès</th><th>Sessions</th><th>Actions</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{roles[a.role]||a.role}</small></td><td><span className="access-tag">{!a.active?'Suspendu':!school.active?'École suspendue':a.connected?'Connexion rattachée':'Connexion à préparer'}</span></td><td>{a.sessions}</td><td><div className="access-row-actions">{!a.connected&&<button disabled={busy||!a.active||!school.active} onClick={()=>open('identity',a)}>Rattacher la connexion</button>}<button disabled={busy} onClick={()=>{if(window.confirm(a.active?`Suspendre ${a.name} et fermer ses sessions ?`:`Réactiver ${a.name} ?`))mutate('/admin/account-status',{id:a.id,active:!a.active});}}>{a.active?'Suspendre':'Réactiver'}</button>{a.sessions>0&&<button disabled={busy} onClick={()=>{if(window.confirm(`Fermer toutes les sessions de ${a.name} ?`))mutate('/admin/revoke',{id:a.id});}}>Fermer les sessions</button>}</div></td></tr>)}</tbody></table></div>}
    <p className="access-footnote">Les identifiants sont remis par votre équipe. Les comptes sans connexion rattachée ne peuvent pas encore se connecter.</p></>:<p>Ajoutez votre premier établissement pour préparer ses accès.</p>}</section></div>
    {form&&<section className="access-panel access-form-panel"><form onSubmit={e=>{e.preventDefault();mutate('/admin/'+({school:'schools',class:'classes',account:'accounts',identity:'identity'}[form]),draft);}}><h2>{{school:'Ajouter une école',class:'Ajouter une classe',account:'Préparer un compte',identity:'Rattacher la connexion'}[form]}</h2><fieldset disabled={busy}>
    {form!=='identity'&&<label>{form==='school'?'Nom de l’école':form==='class'?'Nom de la classe':'Nom et prénom'}<input autoFocus required minLength={form==='school'?3:2} maxLength={form==='school'?140:form==='class'?100:120} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>}
    {form==='account'&&<><label>Rôle<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value,classId:'',childId:''})}>{Object.entries(roles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{draft.role==='parent'?<label>Enfant rattaché<select required value={draft.childId} onChange={e=>setDraft({...draft,childId:e.target.value})}><option value="">Choisir l’enfant</option>{accounts.filter(a=>a.role==='eleve'&&a.active).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>:<label>Classe<select required value={draft.classId} onChange={e=>setDraft({...draft,classId:e.target.value})}><option value="">Choisir une classe</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<p>Le profil sera créé dans {school?.name}. Vous préparerez ensuite sa connexion.</p></>}
    {form==='identity'&&<><p>Compte : <strong>{accounts.find(a=>a.id===draft.id)?.name}</strong></p><ol><li>Créez le compte dans votre tableau de bord Auth0.</li><li>Vérifiez son identité, puis recopiez son « User ID » ci-dessous.</li><li>Remettez les identifiants à l’utilisateur par votre canal habituel.</li></ol><label>User ID Auth0<input autoFocus required placeholder="auth0|…" value={draft.subject} onChange={e=>setDraft({...draft,subject:e.target.value})}/></label><p>Ne saisissez aucun mot de passe ici. La réinitialisation reste gérée depuis Auth0 à cette étape.</p></>}
    <div className="access-toolbar"><button className="access-primary">{busy?'Enregistrement…':'Enregistrer'}</button><button type="button" onClick={()=>setForm(null)}>Annuler</button></div></fieldset></form></section>}
    <details className="access-panel access-history"><summary>Historique des dernières actions</summary>{!data.events.length&&<p>Aucune action enregistrée pour le moment.</p>}{data.events.map((e,i)=><p key={i}><strong>{actions[e.action]||e.action}</strong> · {data.schools.find(s=>s.id===e.targetId)?.name||data.accounts.find(a=>a.id===e.targetId)?.name||'Classe'} · {e.actor} · {new Date(e.createdAt*1000).toLocaleString('fr-MA')}</p>)}</details></>}
    </main></div>;
}
