import { ArrowRight, Buildings, CheckCircle, GraduationCap, Key, Users } from '@phosphor-icons/react/ssr';

const countLabel=(count,singular,plural)=>`${count} ${count===1?singular:plural}`;

export default function AdminHome({data}){
  const activeSchools=data.schools.filter(s=>s.active);
  const pending=data.accounts.filter(a=>a.active&&!a.connected&&activeSchools.some(s=>s.id===a.schoolId));
  const connected=data.accounts.filter(a=>a.connected).length;
  const sessions=data.accounts.reduce((total,a)=>total+a.sessions,0);
  const metrics=[['Écoles',data.schools.length,`${activeSchools.length} active${activeSchools.length===1?'':'s'}`,Buildings],['Comptes scolaires',data.accounts.length,`${connected} connexion${connected===1?'':'s'} rattachée${connected===1?'':'s'}`,Users],['Classes actives',data.classes.length,'Dans vos établissements',GraduationCap],['Sessions ouvertes',sessions,'Comptes scolaires connectés',Key]];
  return <div className="admin-home">
    <section className="admin-metrics" aria-label="Vue d’ensemble des écoles">{metrics.map(([label,value,caption,Icon])=><article className="access-panel" key={label}><span><Icon/>{label}</span><strong>{value}</strong><small>{caption}</small></article>)}</section>
    <div className="admin-home-columns"><section className="access-panel"><div className="admin-section-heading"><h2>Vos établissements</h2><a href="/admin/ecoles-acces">Tout gérer <ArrowRight/></a></div>{data.schools.length?<div className="admin-school-list">{data.schools.map(s=><a href={`/admin/ecoles-acces?ecole=${encodeURIComponent(s.id)}`} key={s.id}><span className="admin-school-icon"><Buildings/></span><span><strong>{s.name}</strong><small>{countLabel(data.accounts.filter(a=>a.schoolId===s.id).length,'compte','comptes')} · {countLabel(data.classes.filter(c=>c.schoolId===s.id).length,'classe active','classes actives')}</small></span><span className={'access-tag'+(s.active?'':' suspended')}>{s.active?'Active':'Suspendue'}</span><ArrowRight/></a>)}</div>:<p>Aucune école pour le moment. Ouvrez la gestion des écoles pour préparer votre premier établissement.</p>}</section>
    <aside className="access-panel admin-next"><span className="admin-next-icon">{pending.length?<Key/>:<CheckCircle/>}</span><h2>{!data.accounts.length?'Les premiers accès':pending.length?`${pending.length} connexion${pending.length===1?'':'s'} à préparer`:'Aucune connexion en attente'}</h2><p>{!data.accounts.length?'Préparez le compte Direction et les classes, puis les comptes individuels des enseignants, des élèves et de leurs parents.':pending.length?'Ces comptes actifs attendent leur rattachement à Auth0 pour pouvoir se connecter.':'Aucun compte actif d’une école ouverte n’attend de rattachement. Pensez à remettre les identifiants en privé.'}</p><a className="access-primary" href="/admin/ecoles-acces">{pending.length?'Préparer les accès':'Gérer les comptes'} <ArrowRight/></a><a className="admin-help-link" href="/guide-ecole">Comment accueillir une école ? <ArrowRight/></a></aside></div>
    <details className="admin-demo-tools"><summary>Outils éditoriaux en démonstration</summary><p>La démonstration conserve ses exemples de bibliothèque et de médias. Elle ne modifie ni les comptes scolaires ni les documents privés. Pour les documents autorisés, utilisez Bibliothèque ; pour les publications raccordées, utilisez Blog & articles.</p><a href="/connexion/admin">Ouvrir la démonstration éditoriale <ArrowRight/></a></details>
  </div>;
}
