import {PrivateManualEntry} from './PrivateManualEntry.jsx';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,Buildings,CaretRight,CheckCircle,DownloadSimple,Eye,FileText,Key,Plus,ShieldCheck,WarningCircle} from '@phosphor-icons/react/ssr';
import PageHeader from '../../PageHeader.jsx';
import {DataTable,ProgressBar} from '../../TableAndProgress.jsx';
import {RoleKpis,RoleActionList} from '../beta-roles/BetaRolePages.jsx';
import {directorModel,directorPath,directorPercent,directorPercentLabel} from './directorCore.js';

export const DIRECTOR_TITLES={accueil:'Vue d’ensemble',actions:'Priorités',classes:'Classes',enseignants:'Enseignants',affectations:'Affectations',eleves:'Élèves & activation','suivi-utilisation':'Suivi d’utilisation',etablissement:'Établissement',rapports:'Rapports',aide:'Aide & assistance'};
export const DIRECTOR_REPORTS=[['summary','Synthèse de l’établissement'],['classes','Suivi des classes'],['activation','Suivi des activations']];
const managed='Les comptes, classes, rattachements et codes sont gérés par l’administration Jet d’Encre.';
const date=value=>value?new Intl.DateTimeFormat('fr-MA',{dateStyle:'medium',timeZone:'Africa/Casablanca'}).format(new Date(value)):'Aucune trace';
const percent=(n,d)=>directorPercentLabel(directorPercent(n,d));
function Empty(){return <p className="school-library-note" role="status">Aucun résultat dans cette vue.</p>;}
function Managed({children}){return <p className="school-library-note">{children||managed}</p>;}
function UnavailableButton({children}){return <button className="button button-light" disabled title={managed}>{children}</button>;}

// Existing Direction composition, shared headers/tables/KPIs and original Pen class names.
// No DemoProvider, browser fixture KPI or simulated notification is used as school data.
export default function SchoolDirectorPages({snapshot,user,selection,days,onDays,onExport,Link}){
 const [query,setQuery]=useState(''),[teacherId,setTeacherId]=useState('');
 const {section,detail}=selection,model=directorModel(snapshot,{days,query}),{totals}=model;
 const search=label=><div className="filter-bar"><label>{label}<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un nom"/></label><span>Filtre de cette liste uniquement</span></div>;
 const exportButton=kind=><button className="button button-light" onClick={()=>onExport(kind)}><DownloadSimple/> Exporter le CSV</button>;
 const back=(section,label)=><Link to={directorPath(section)} className="button button-light"><ArrowLeft/> {label}</Link>;
 const nameOf=id=>snapshot.classes.find(c=>c.id===id)?.name;
 const classNames=ids=>ids.map(nameOf).filter(Boolean).join(' · ')||'Sans classe active';
 const activityControl=<label>Période d’activité<select value={days} onChange={e=>onDays(e.target.value)}><option value="7">7 derniers jours</option><option value="30">30 derniers jours</option></select></label>;
 const classRows=rows=>rows.map(c=>[c.name,c.students.length,c.teachers.map(t=>t.name).join(' · ')||'Non affecté',`${c.activated} / ${c.students.length}`,`${c.recent} / ${c.students.length}`,<Link to={directorPath('classes',c.id)} className="icon-button" aria-label={'Ouvrir la classe '+c.name}><CaretRight/></Link>]);
 const table=rows=><><DataTable label="Classes de l’établissement" headers={['Classe','Élèves','Enseignants','Manuel activé','Activité · '+days+' jours','Fiche']} rows={classRows(rows)}/><Managed>Activité sur les {days} derniers jours ; les autres valeurs sont cumulatives. Un élève peut figurer dans plusieurs classes : ne pas additionner les lignes.</Managed></>;
 const missing=selection.invalid||(detail&&section==='classes'&&!model.classes.some(c=>c.id===detail))||(detail&&section==='enseignants'&&!snapshot.teachers.some(t=>t.id===detail))||(detail&&section==='rapports'&&!DIRECTOR_REPORTS.some(r=>r[0]===detail));
 if(missing)return <><PageHeader eyebrow="DIRECTION" title="Cette page n’est pas disponible" subtitle="Le lien est invalide ou ne correspond plus à votre établissement."/>{back('accueil','Revenir à la vue d’ensemble')}</>;

 if(section==='accueil')return <>
  <PageHeader eyebrow={snapshot.schoolName+' · BETA'} title="Piloter l’adoption pédagogique" subtitle="Une vue cohérente de l’activation, de l’activité enregistrée et des points à accompagner." action={<Link to={directorPath('actions')} className="button button-dark">Voir les priorités <ArrowRight/></Link>}/>
  <RoleKpis items={[["Élèves avec manuel",`${totals.activated} / ${totals.students}`,percent(totals.activated,totals.students)],["Classes actives",totals.classes,`${totals.unassigned} sans enseignant`],["Activité récente",`${totals.recent} / ${totals.students}`,days+' derniers jours'],["Enseignants",totals.teachers,'Comptes actifs','gold']]}/>
  <section className="beta-role-grid"><article className="panel"><div className="beta-role-heading"><div><span>MES CLASSES</span><h2>Suivi de l’établissement</h2></div><Link to={directorPath('classes')}>Voir les classes</Link></div><div className="beta-role-class-list">{model.classes.map(c=><article key={c.id}><span><Buildings/></span><div><strong><Link to={directorPath('classes',c.id)}>{c.name}</Link></strong><small>{c.teachers.length?'Enseignant affecté':'Aucun enseignant affecté'} · {c.activated}/{c.students.length} avec manuel</small></div><i>{c.recent}/{c.students.length} actifs récemment</i></article>)}</div>{!model.classes.length&&<Empty/>}</article><article className="panel beta-role-next"><span>À EXAMINER</span><WarningCircle weight="duotone"/><h2>{model.priorities.length} repère{model.priorities.length===1?'':'s'} à vérifier</h2><p>Vérifiez les conditions d’accès et le calendrier pédagogique avant d’interpréter l’activité.</p><Link to={directorPath('actions')} className="button button-light">Voir les priorités <ArrowRight/></Link></article></section>
 </>;
 if(section==='actions')return <><PageHeader eyebrow="CENTRE D’ACTIONS DIRECTION" title="Priorités de l’établissement" subtitle="Chaque repère relie un constat, une précaution d’interprétation et une action."/><section className="panel">{model.priorities.length?<RoleActionList actions={model.priorities.map(p=>({...p,priority:p.id==='unassigned'?'high':'medium',icon:p.id==='activation'?<Key/>:<WarningCircle/>,meta:p.count+' concerné(s)',route:directorPath(p.section),action:'Examiner le suivi'}))} resolutions={new Map()} RouteLink={Link}/>:<p>Aucun repère à signaler dans les données disponibles. Cela ne constitue pas une évaluation pédagogique.</p>}</section><Managed>Les repères sont recalculés à partir des comptes. Aucun bouton ne les marque artificiellement comme résolus.</Managed></>;
 if(section==='classes'&&detail){const c=model.classes.find(c=>c.id===detail);return <><PageHeader eyebrow="ORGANISATION" title={'Classe '+c.name} subtitle={snapshot.schoolName} action={back('classes','Retour aux classes')}/><section className="panel pen-editor-form"><label>Nom de la classe<input readOnly value={c.name}/></label><label>Enseignants rattachés<input readOnly value={c.teachers.map(t=>t.name).join(' · ')||'Non affecté'}/></label><Managed/></section><h2>Élèves de la classe</h2><DataTable label="Élèves de la classe" headers={['Élève','Manuel activé','Dernière activité','XP cumulés']} rows={c.students.map(s=>[s.name,s.manuals?'Oui':'Non',date(s.lastActiveAt),s.xp])}/>{!c.students.length&&<Empty/>}</>;}
 if(section==='classes')return <><PageHeader eyebrow="ORGANISATION" title="Classes de l’établissement" subtitle={`${totals.classes} classes actives · ${totals.students} élèves actifs`} action={<UnavailableButton><Plus/> Créer une classe</UnavailableButton>}/><Managed/>{search('Rechercher une classe')}{table(model.visibleClasses)}{!model.visibleClasses.length&&<Empty/>}</>;
 if(section==='enseignants'&&detail){const t=snapshot.teachers.find(t=>t.id===detail);return <><PageHeader eyebrow="ÉQUIPE PÉDAGOGIQUE" title={t.name} subtitle={classNames(t.classIds)} action={back('enseignants','Retour aux enseignants')}/><RoleKpis items={[["Classes",t.classIds.length,'Rattachements actifs'],["Devoirs publiés",t.assignments,'Cumul dans cette école'],["Corrections publiées",t.reviews,'Cumul dans cette école']]}/><section className="panel"><h2>Classes rattachées</h2>{table(model.classes.filter(c=>t.classIds.includes(c.id)))}</section><Managed>Les productions, notes individuelles et commentaires des élèves restent dans les espaces pédagogiques autorisés. Les durées et connexions ne sont pas mesurées ici.</Managed></>;}
 if(section==='enseignants')return <><PageHeader eyebrow="ÉQUIPE PÉDAGOGIQUE" title="Enseignants" subtitle="Consultez les rattachements et les publications enregistrées." action={<UnavailableButton><Plus/> Inviter un enseignant</UnavailableButton>}/><Managed/>{search('Rechercher un enseignant')}<DataTable label="Liste des enseignants" headers={['Enseignant','Classes','Devoirs publiés','Corrections publiées','Fiche']} rows={model.visibleTeachers.map(t=>[t.name,classNames(t.classIds),t.assignments,t.reviews,<Link to={directorPath('enseignants',t.id)} className="icon-button" aria-label={'Ouvrir le profil de '+t.name}><CaretRight/></Link>])}/>{!model.visibleTeachers.length&&<Empty/>}</>;
 if(section==='affectations'){const teacher=snapshot.teachers.find(t=>t.id===teacherId)||snapshot.teachers[0];return <><PageHeader eyebrow="ÉTABLISSEMENT · AFFECTATIONS" title="Affectations des enseignants" subtitle="Consultez les associations enregistrées entre enseignants et classes."/><Managed/><div className="pen-assignment-columns"><section><h2>1. Enseignant</h2>{snapshot.teachers.map(t=><button type="button" className={teacher?.id===t.id?'active':''} aria-pressed={teacher?.id===t.id} key={t.id} onClick={()=>setTeacherId(t.id)}><span>{t.name[0]}</span><span><strong>{t.name}</strong><small>{t.classIds.length} classe(s) active(s)</small></span></button>)}{!snapshot.teachers.length&&<Empty/>}</section><section><h2>2. Classes</h2>{snapshot.classes.map(c=><label className={teacher?.classIds.includes(c.id)?'active':''} key={c.id}><input type="checkbox" disabled checked={Boolean(teacher?.classIds.includes(c.id))}/><span><strong>{c.name}</strong><small>{model.classes.find(x=>x.id===c.id).teachers.length?'Enseignant rattaché':'Sans enseignant'}</small></span></label>)}</section><section><h2>3. Vérification</h2><div className="pen-summary-card"><strong>{teacher?.name||'Aucun enseignant'}</strong><span>{teacher?classNames(teacher.classIds):'Aucune classe'}</span><small>Charge horaire et conflits d’emploi du temps non mesurés.</small></div><Managed>Pour corriger un rattachement, transmettre la demande à votre interlocuteur Jet d’Encre. Aucun changement n’est enregistré depuis cette vue.</Managed></section></div></>;}
 if(section==='eleves')return <><PageHeader eyebrow="ÉLÈVES & ACTIVATION" title="Piloter les activations" subtitle="Distinguez les comptes actifs des manuels effectivement activés." action={<UnavailableButton><Key/> Générer un lot</UnavailableButton>}/><Managed/><div className="pen-activation-overview"><div><strong>{percent(totals.activated,totals.students)}</strong><span>{totals.activated} élèves avec manuel sur {totals.students}</span></div>{totals.students>0?<ProgressBar value={directorPercent(totals.activated,totals.students)} label="Manuel activé"/>:<span>Aucun élève actif</span>}<UnavailableButton>Relancer les familles</UnavailableButton></div><Managed>Les envois de relance ne sont pas raccordés. Un manuel activé n’est pas une preuve de lecture.</Managed>{search('Rechercher un élève')}<DataTable label="Activation des élèves" headers={['Élève','Classes actives','Manuels activés']} rows={model.visibleStudents.map(s=>[s.name,classNames(s.classIds),s.manuals])}/>{!model.visibleStudents.length&&<Empty/>}</>;
 if(section==='suivi-utilisation')return <><PageHeader eyebrow="ADOPTION PÉDAGOGIQUE" title="Utilisation de la plateforme" subtitle="L’activité enregistrée ne mesure ni le temps passé ni le niveau de français."/><div className="filter-bar">{activityControl}<span>Les effectifs et XP restent cumulatifs.</span></div><RoleKpis items={[["Activité récente",`${totals.recent} / ${totals.students}`,days+' derniers jours'],["XP cumulés",totals.xp,'Sept jeux raccordés'],["Temps moyen",'—','Non mesuré'],["Connexions",'—','Non mesurées']]}/>{table(model.classes)}<Managed>{snapshot.definitions.activity} Les élèves de plusieurs classes figurent dans chaque classe ; les lignes ne doivent pas être additionnées.</Managed></>;
 if(section==='etablissement')return <><PrivateManualEntry role='directeur'/><PageHeader eyebrow="ÉTABLISSEMENT" title={snapshot.schoolName} subtitle="Référentiel associé au compte connecté" action={<UnavailableButton><Buildings/> Modifier la fiche</UnavailableButton>}/><Managed/><div className="pen-school-grid"><section className="panel"><h2>Profil de l’établissement</h2><dl><div><dt>Compte Direction</dt><dd>{user.name}</dd></div><div><dt>Classes actives</dt><dd>{totals.classes}</dd></div><div><dt>Enseignants actifs</dt><dd>{totals.teachers}</dd></div><div><dt>Licence contractuelle</dt><dd>Non renseignée</dd></div></dl></section><section className="panel"><h2>Santé du service</h2><p>Ces mesures ne sont pas encore disponibles.</p><p>Aucun taux de disponibilité ou de synchronisation n’est déduit de l’activité pédagogique.</p></section><aside className="panel pen-assistance"><ShieldCheck weight="duotone"/><h2>Besoin d’assistance ?</h2><p>Aucun ticket n’est créé automatiquement.</p><Link to={directorPath('aide')} className="button button-gold">Consulter l’aide</Link><Link to={directorPath('actions')} className="button button-light">Voir les priorités</Link></aside></div></>;
 if(section==='rapports'&&detail){const title=DIRECTOR_REPORTS.find(r=>r[0]===detail)[1];return <><PageHeader eyebrow="RAPPORT D’ÉTABLISSEMENT" title={title} subtitle={'Calculé le '+date(snapshot.generatedAt)} action={back('rapports','Retour aux rapports')}/><div className="filter-bar">{activityControl}{exportButton(detail)}</div>{detail==='classes'?table(model.classes):detail==='activation'?<DataTable label="Rapport des activations" headers={['Élève','Classes actives','Manuels activés']} rows={snapshot.students.map(s=>[s.name,classNames(s.classIds),s.manuals])}/>:<DataTable label="Synthèse de l’établissement" headers={['Indicateur','Valeur']} rows={[["Élèves actifs",totals.students],["Enseignants actifs",totals.teachers],["Classes actives",totals.classes],["Élèves avec manuel",totals.activated],["Élèves avec activité récente",totals.recent],["XP cumulés",totals.xp],["Classes sans enseignant",totals.unassigned],["Élèves sans classe active",totals.unplaced]]}/>}<Managed>{snapshot.definitions.scope} {snapshot.definitions.xp}</Managed></>;}
 if(section==='rapports')return <><PageHeader eyebrow="RAPPORTS" title="Rapports de pilotage" subtitle="Consultez et exportez une synthèse actualisée de votre établissement."/><div className="report-grid">{DIRECTOR_REPORTS.map(([id,title])=><article key={id}><span><FileText weight="duotone"/></span><h3>{title}</h3><p>{date(snapshot.generatedAt)}</p><i className="status-pill success">Disponible</i><div><Link to={directorPath('rapports',id)} className="button button-light"><Eye/> Consulter</Link><button className="icon-button" onClick={()=>onExport(id)} aria-label={'Télécharger '+title}><DownloadSimple/></button></div></article>)}<article><span><FileText weight="duotone"/></span><h3>Progression comparable en français</h3><p>Des évaluations comparables sont nécessaires avant de produire ce rapport.</p><i className="status-pill warning">Non mesurée</i></article></div></>;
 return <><PageHeader eyebrow="DIRECTION" title="Aide & assistance" subtitle="Les accès sont préparés par Jet d’Encre et remis en privé."/><section className="panel"><h2>Faire corriger une information</h2><p>{managed} Signalez à votre interlocuteur habituel l’établissement et la classe concernés, sans transmettre de mot de passe ni de code complet.</p><a className="button button-light" href="/guide-ecole">Ouvrir le guide école</a><p>Aucun contact non vérifié ni ticket fictif n’est présenté comme un service opérationnel.</p></section></>;
}
