export const WORD_CHOICE_LEVELS = Object.freeze([
  "3e AEP",
  "4e AEP",
  "5e AEP",
  "6e AEP",
]);

export const WORD_CHOICE_CATEGORIES = Object.freeze([
  "Lexique",
  "Accords",
  "Conjugaison",
  "Connecteurs",
]);

const createItem = ({
  id,
  level,
  category,
  prompt,
  choices,
  correctIndex,
  explanation,
  learningGoal,
}) => Object.freeze({
  id,
  level,
  category,
  prompt,
  choices: Object.freeze([...choices]),
  correctIndex,
  explanation,
  learningGoal,
});

/**
 * Banque éditoriale du jeu « Le Mot juste ».
 * Chaque phrase place la langue dans une situation familière à un élève marocain,
 * sans supposer une ville, une langue familiale ou un milieu social particuliers.
 */
export const wordChoiceItems = Object.freeze([
  createItem({
    id: "mot-juste-01",
    level: "3e AEP",
    category: "Lexique",
    prompt: "Pour préparer le thé, Salma fait ___ l’eau.",
    choices: ["bouillir", "dormir", "cueillir", "courir"],
    correctIndex: 0,
    explanation: "On fait bouillir l’eau : elle chauffe jusqu’à produire de la vapeur.",
    learningGoal: "Choisir un verbe précis dans une situation quotidienne.",
  }),
  createItem({
    id: "mot-juste-02",
    level: "4e AEP",
    category: "Lexique",
    prompt: "À la bibliothèque, Amine ___ un livre pour la semaine.",
    choices: ["répare", "emprunte", "dessine", "mesure"],
    correctIndex: 1,
    explanation: "Emprunter un livre, c’est le prendre pour un temps avant de le rendre.",
    learningGoal: "Employer le vocabulaire des lieux de lecture.",
  }),
  createItem({
    id: "mot-juste-03",
    level: "5e AEP",
    category: "Lexique",
    prompt: "Le plan nous aide à nous ___ dans les ruelles de la médina.",
    choices: ["abriter", "orienter", "reposer", "réunir"],
    correctIndex: 1,
    explanation: "S’orienter signifie trouver sa direction et savoir où l’on se situe.",
    learningGoal: "Comprendre un verbe grâce au contexte.",
  }),
  createItem({
    id: "mot-juste-04",
    level: "6e AEP",
    category: "Lexique",
    prompt: "Après l’averse, les pavés de la place ___ sous le soleil.",
    choices: ["murmurent", "scintillent", "s’effacent", "s’endorment"],
    correctIndex: 1,
    explanation: "Scintiller signifie briller par petits éclats, comme une surface encore mouillée.",
    learningGoal: "Enrichir le vocabulaire descriptif.",
  }),
  createItem({
    id: "mot-juste-05",
    level: "4e AEP",
    category: "Lexique",
    prompt: "Au marché, le marchand pèse les oranges avec une ___.",
    choices: ["boussole", "balance", "règle", "loupe"],
    correctIndex: 1,
    explanation: "Une balance est un instrument qui sert à mesurer la masse d’un produit.",
    learningGoal: "Nommer un objet d’usage courant.",
  }),
  createItem({
    id: "mot-juste-06",
    level: "3e AEP",
    category: "Accords",
    prompt: "Dans le panier, les oranges sont bien ___.",
    choices: ["frais", "fraîche", "fraîches", "fraîchement"],
    correctIndex: 2,
    explanation: "« Oranges » est féminin pluriel : l’adjectif s’écrit donc « fraîches ».",
    learningGoal: "Accorder un adjectif au féminin pluriel.",
  }),
  createItem({
    id: "mot-juste-07",
    level: "4e AEP",
    category: "Accords",
    prompt: "Yasmine porte une veste ___ pour la sortie scolaire.",
    choices: ["bleu", "bleue", "bleus", "bleues"],
    correctIndex: 1,
    explanation: "« Veste » est féminin singulier : on ajoute un e à l’adjectif « bleu ».",
    learningGoal: "Accorder un adjectif au féminin singulier.",
  }),
  createItem({
    id: "mot-juste-08",
    level: "5e AEP",
    category: "Accords",
    prompt: "Les élèves ont préparé des affiches très ___.",
    choices: ["coloré", "colorée", "colorés", "colorées"],
    correctIndex: 3,
    explanation: "« Affiches » est féminin pluriel : l’adjectif devient « colorées ».",
    learningGoal: "Repérer le nom qui commande l’accord.",
  }),
  createItem({
    id: "mot-juste-09",
    level: "6e AEP",
    category: "Accords",
    prompt: "Les histoires que nous avons ___ en classe parlent de voyage.",
    choices: ["lu", "lue", "lus", "lues"],
    correctIndex: 3,
    explanation: "Le complément « les histoires » est placé avant « avons lues » : le participe passé s’accorde au féminin pluriel.",
    learningGoal: "Accorder un participe passé employé avec avoir quand le complément le précède.",
  }),
  createItem({
    id: "mot-juste-10",
    level: "5e AEP",
    category: "Accords",
    prompt: "Cette ruelle et ce jardin sont ___ le matin.",
    choices: ["calme", "calmes", "calmée", "calmement"],
    correctIndex: 1,
    explanation: "Deux noms forment un groupe pluriel : l’adjectif qualificatif s’écrit « calmes ».",
    learningGoal: "Accorder un adjectif avec plusieurs noms.",
  }),
  createItem({
    id: "mot-juste-11",
    level: "3e AEP",
    category: "Conjugaison",
    prompt: "Chaque matin, je ___ mon cartable avant de partir.",
    choices: ["prépare", "prépares", "préparons", "préparent"],
    correctIndex: 0,
    explanation: "Avec le sujet « je », le verbe préparer au présent s’écrit « je prépare ».",
    learningGoal: "Conjuguer un verbe en -er au présent.",
  }),
  createItem({
    id: "mot-juste-12",
    level: "4e AEP",
    category: "Conjugaison",
    prompt: "Hier, nous ___ le musée avec notre classe.",
    choices: ["visitons", "visiterons", "avons visité", "visitions demain"],
    correctIndex: 2,
    explanation: "Le mot « hier » indique une action passée : « avons visité » est au passé composé.",
    learningGoal: "Choisir un temps grâce à un indicateur temporel.",
  }),
  createItem({
    id: "mot-juste-13",
    level: "5e AEP",
    category: "Conjugaison",
    prompt: "Demain, vous ___ au tournoi de l’école.",
    choices: ["participez hier", "participerez", "participiez", "participer"],
    correctIndex: 1,
    explanation: "« Demain » annonce le futur : avec « vous », on écrit « vous participerez ».",
    learningGoal: "Conjuguer un verbe au futur simple.",
  }),
  createItem({
    id: "mot-juste-14",
    level: "6e AEP",
    category: "Conjugaison",
    prompt: "Si j’avais davantage de temps, je ___ plus souvent.",
    choices: ["lis", "lirais", "lirai", "lise"],
    correctIndex: 1,
    explanation: "Après « si j’avais », on emploie le conditionnel présent : « je lirais ».",
    learningGoal: "Reconnaître le conditionnel dans une hypothèse.",
  }),
  createItem({
    id: "mot-juste-15",
    level: "4e AEP",
    category: "Conjugaison",
    prompt: "En ce moment, les enfants ___ au ballon dans la cour.",
    choices: ["joue", "joues", "jouons", "jouent"],
    correctIndex: 3,
    explanation: "Le sujet « les enfants » correspond à « ils » : au présent, on écrit « jouent ».",
    learningGoal: "Accorder le verbe avec un sujet au pluriel.",
  }),
  createItem({
    id: "mot-juste-16",
    level: "3e AEP",
    category: "Connecteurs",
    prompt: "Je prends mon parapluie ___ la pluie tombe.",
    choices: ["parce que", "mais", "puis", "pourtant"],
    correctIndex: 0,
    explanation: "« Parce que la pluie tombe » donne la cause : la pluie explique pourquoi je prends mon parapluie.",
    learningGoal: "Exprimer une cause avec « parce que ».",
  }),
  createItem({
    id: "mot-juste-17",
    level: "4e AEP",
    category: "Connecteurs",
    prompt: "Nous avons fini nos devoirs, ___ nous pouvons jouer.",
    choices: ["car", "donc", "mais", "avant"],
    correctIndex: 1,
    explanation: "« Donc » introduit la conséquence : les devoirs sont terminés, alors le jeu devient possible.",
    learningGoal: "Exprimer une conséquence avec « donc ».",
  }),
  createItem({
    id: "mot-juste-18",
    level: "5e AEP",
    category: "Connecteurs",
    prompt: "Le chemin est long, ___ le paysage est magnifique.",
    choices: ["parce que", "donc", "mais", "afin que"],
    correctIndex: 2,
    explanation: "« Mais » oppose deux idées : la longueur du chemin et la beauté du paysage.",
    learningGoal: "Relier deux idées opposées.",
  }),
  createItem({
    id: "mot-juste-19",
    level: "6e AEP",
    category: "Connecteurs",
    prompt: "___ le temps est frais, nous marchons au bord de la mer.",
    choices: ["Parce que", "Même si", "Afin que", "Depuis que"],
    correctIndex: 1,
    explanation: "« Même si le temps est frais » exprime une concession : le froid n’empêche pas la promenade.",
    learningGoal: "Exprimer une concession avec « même si ».",
  }),
  createItem({
    id: "mot-juste-20",
    level: "6e AEP",
    category: "Connecteurs",
    prompt: "Meryem relit son texte ___ corriger les erreurs.",
    choices: ["malgré", "afin de", "tandis que", "puisque"],
    correctIndex: 1,
    explanation: "« Afin de » introduit le but : Meryem relit son texte pour corriger les erreurs.",
    learningGoal: "Exprimer un but avec « afin de ».",
  }),
]);

export default wordChoiceItems;
