const createQuestion = ({
  id,
  theme,
  level,
  prompt,
  choices,
  correctIndex,
  explanation,
}) =>
  Object.freeze({
    id,
    theme,
    level,
    prompt,
    choices: Object.freeze([...choices]),
    correctIndex,
    explanation,
  });

export const cultureQuizQuestions = Object.freeze([
  createQuestion({
    id: "culture-01",
    theme: "Culture générale · Maroc",
    level: "facile",
    prompt: "Quel océan borde la côte ouest du Maroc ?",
    choices: [
      "La mer Méditerranée",
      "L’océan Atlantique",
      "L’océan Indien",
      "L’océan Pacifique",
    ],
    correctIndex: 1,
    explanation: "L’océan Atlantique borde toute la côte ouest du Maroc.",
  }),
  createQuestion({
    id: "culture-02",
    theme: "Maroc",
    level: "facile",
    prompt: "Quelle monnaie utilise-t-on au Maroc ?",
    choices: ["L’euro", "Le dinar", "Le dirham", "Le dollar"],
    correctIndex: 2,
    explanation: "La monnaie officielle du Maroc est le dirham marocain.",
  }),
  createQuestion({
    id: "culture-03",
    theme: "Géographie",
    level: "intermédiaire",
    prompt: "Quel est le plus haut sommet du Maroc ?",
    choices: ["Le Toubkal", "Le M’Goun", "Le Siroua", "Le Tidighine"],
    correctIndex: 0,
    explanation: "Le Toubkal est le plus haut sommet du Maroc et d’Afrique du Nord.",
  }),
  createQuestion({
    id: "culture-04",
    theme: "Patrimoine marocain",
    level: "facile",
    prompt: "Dans quelle ville se trouve la mosquée Hassan-II ?",
    choices: ["Rabat", "Tanger", "Casablanca", "Meknès"],
    correctIndex: 2,
    explanation: "La mosquée Hassan-II se trouve au bord de l’océan, à Casablanca.",
  }),
  createQuestion({
    id: "culture-05",
    theme: "Littérature",
    level: "intermédiaire",
    prompt: "Qui a écrit « Le Petit Prince » ?",
    choices: [
      "Victor Hugo",
      "Antoine de Saint-Exupéry",
      "Jules Verne",
      "Molière",
    ],
    correctIndex: 1,
    explanation: "Antoine de Saint-Exupéry a publié « Le Petit Prince » en 1943.",
  }),
  createQuestion({
    id: "culture-06",
    theme: "Sciences",
    level: "facile",
    prompt: "Quelle planète appelle-t-on « la planète rouge » ?",
    choices: ["Vénus", "Jupiter", "Mars", "Mercure"],
    correctIndex: 2,
    explanation: "Mars paraît rouge à cause du fer oxydé présent à sa surface.",
  }),
  createQuestion({
    id: "culture-07",
    theme: "Sciences",
    level: "facile",
    prompt: "À quelle température l’eau pure gèle-t-elle ?",
    choices: ["−10 °C", "0 °C", "10 °C", "100 °C"],
    correctIndex: 1,
    explanation: "À pression normale, l’eau pure gèle à 0 °C.",
  }),
  createQuestion({
    id: "culture-08",
    theme: "Géographie",
    level: "facile",
    prompt: "Quel est le plus grand océan du monde ?",
    choices: [
      "L’océan Atlantique",
      "L’océan Indien",
      "L’océan Arctique",
      "L’océan Pacifique",
    ],
    correctIndex: 3,
    explanation: "L’océan Pacifique couvre une plus grande surface que tous les autres océans.",
  }),
  createQuestion({
    id: "culture-09",
    theme: "Monde francophone",
    level: "intermédiaire",
    prompt: "Quelle est la capitale du Sénégal ?",
    choices: ["Dakar", "Bamako", "Tunis", "Abidjan"],
    correctIndex: 0,
    explanation: "Dakar est la capitale du Sénégal, sur la côte atlantique.",
  }),
  createQuestion({
    id: "culture-10",
    theme: "Histoire",
    level: "facile",
    prompt: "Dans quel pays se trouvent les pyramides de Gizeh ?",
    choices: ["La Grèce", "Le Mexique", "L’Égypte", "L’Italie"],
    correctIndex: 2,
    explanation: "Les pyramides de Gizeh ont été construites dans l’Égypte antique.",
  }),
  createQuestion({
    id: "culture-11",
    theme: "Histoire et sport",
    level: "intermédiaire",
    prompt: "Dans quel pays les Jeux olympiques antiques sont-ils nés ?",
    choices: ["L’Italie", "La Grèce", "La France", "L’Égypte"],
    correctIndex: 1,
    explanation: "Les Jeux olympiques antiques sont nés à Olympie, en Grèce.",
  }),
  createQuestion({
    id: "culture-12",
    theme: "Arts",
    level: "intermédiaire",
    prompt: "Quel artiste a peint « La Joconde » ?",
    choices: [
      "Pablo Picasso",
      "Vincent van Gogh",
      "Léonard de Vinci",
      "Claude Monet",
    ],
    correctIndex: 2,
    explanation: "Léonard de Vinci a peint « La Joconde » à la Renaissance.",
  }),
]);

export default cultureQuizQuestions;
