export const EXTRA_FACILE_GRIDS = Object.freeze([
  {
    id: "jet-encre-mf-facile-02",
    version: 1,
    rewardVersion: 1,
    levelId: "facile",
    level: "Facile",
    cefr: "A1",
    title: "Ma journée en classe",
    theme: "Mots, activités et moments de la vie scolaire",
    xp: 20,
    rows: 10,
    cols: 10,
    entries: [
      { id: "F02-01", answer: "DOIGT", clue: "Partie de la main qui montre ou tient un crayon", cellClue: "Partie de la main", definition: "Partie mobile au bout de la main, utile pour toucher, montrer et tenir des objets.", lexicalLabel: "nom masculin", example: "Lina lève un doigt pour répondre à la question.", direction: "across", clueRow: 5, clueCol: 1, row: 5, col: 2, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/doigt" },
      { id: "F02-02", answer: "GOMME", clue: "Petit objet utilisé pour effacer le crayon", cellClue: "Efface les traits de crayon", definition: "Petit objet souple qui enlève les traces laissées par un crayon sur le papier.", lexicalLabel: "nom féminin", example: "Yassine utilise sa gomme pour corriger son dessin.", direction: "down", clueRow: 4, clueCol: 5, row: 5, col: 5, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/gomme" },
      { id: "F02-03", answer: "ÉLÈVE", clue: "Enfant ou jeune qui apprend avec un enseignant", cellClue: "Jeune qui apprend en classe", definition: "Personne qui reçoit un enseignement dans une classe ou auprès d’un professeur.", lexicalLabel: "nom masculin ou féminin", example: "Chaque élève prépare son cahier avant le cours.", direction: "across", clueRow: 9, clueCol: 0, row: 9, col: 1, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/élève" },
      { id: "F02-04", answer: "NOTE", clue: "Résultat chiffré donné à un travail scolaire", cellClue: "Résultat chiffré", definition: "Nombre ou appréciation donné après l’évaluation d’un exercice ou d’un travail.", lexicalLabel: "nom féminin", example: "Sara obtient une bonne note à son exercice de lecture.", direction: "across", clueRow: 2, clueCol: 0, row: 2, col: 1, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/note" },
      { id: "F02-05", answer: "COPIE", clue: "Feuille où un élève écrit ses réponses", cellClue: "Feuille avec des réponses", definition: "Feuille remise à l’enseignant après avoir écrit les réponses demandées.", lexicalLabel: "nom féminin", example: "L’élève relit sa copie avant de la rendre.", direction: "down", clueRow: 4, clueCol: 8, row: 5, col: 8, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/copie" },
      { id: "F02-06", answer: "OUI", clue: "Mot utilisé pour donner une réponse positive", cellClue: "Réponse positive", definition: "Petit mot employé pour accepter, confirmer ou répondre de manière positive.", lexicalLabel: "adverbe", example: "Nora répond oui quand la maîtresse l’appelle.", direction: "across", clueRow: 3, clueCol: 5, row: 3, col: 6, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/oui" },
      { id: "F02-07", answer: "MOT", clue: "Groupe de lettres qui porte un sens", cellClue: "Groupe de lettres avec un sens", definition: "Unité de langue formée de lettres et utilisée pour nommer, décrire ou agir.", lexicalLabel: "nom masculin", example: "Le mot « école » commence par la lettre E.", direction: "across", clueRow: 6, clueCol: 6, row: 6, col: 7, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/mot" },
      { id: "F02-08", answer: "JUS", clue: "Boisson faite avec des fruits pressés", cellClue: "Boisson de fruits pressés", definition: "Boisson obtenue en pressant des fruits, parfois servie fraîche au goûter.", lexicalLabel: "nom masculin", example: "Amine boit un jus d’orange pendant la pause.", direction: "across", clueRow: 1, clueCol: 3, row: 1, col: 4, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/jus" },
      { id: "F02-09", answer: "JEUDI", clue: "Jour placé entre mercredi et vendredi", cellClue: "Jour après mercredi", definition: "Quatrième jour de la semaine scolaire, situé après mercredi et avant vendredi.", lexicalLabel: "nom masculin", example: "Le jeudi, la classe commence par une séance de lecture.", direction: "down", clueRow: 0, clueCol: 4, row: 1, col: 4, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/jeudi" },
      { id: "F02-10", answer: "MATIN", clue: "Partie de la journée avant midi", cellClue: "Avant midi", definition: "Première partie de la journée, depuis le réveil jusqu’au milieu du jour.", lexicalLabel: "nom masculin", example: "Chaque matin, Salma prend le car pour aller en classe.", direction: "across", clueRow: 8, clueCol: 4, row: 8, col: 5, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/matin" },
      { id: "F02-11", answer: "SPORT", clue: "Activité physique pratiquée avec des règles", cellClue: "Activité physique", definition: "Activité qui fait bouger le corps et peut se pratiquer seul ou en équipe.", lexicalLabel: "nom masculin", example: "Les élèves font du sport dans la cour le mercredi.", direction: "down", clueRow: 0, clueCol: 6, row: 1, col: 6, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/sport" },
    ],
  },
  {
    id: "jet-encre-mf-facile-03",
    version: 1,
    rewardVersion: 1,
    levelId: "facile",
    level: "Facile",
    cefr: "A1",
    title: "Chez moi, en famille",
    theme: "Personnes, pièces et objets de la maison",
    xp: 20,
    rows: 10,
    cols: 10,
    entries: [
      { id: "F03-01", answer: "PRISE", clue: "Point du mur où l’on branche un appareil", cellClue: "Pour brancher un appareil", definition: "Élément fixé au mur qui permet de relier un appareil au courant électrique.", lexicalLabel: "nom féminin", example: "Papa branche la lampe sur la prise du salon.", direction: "down", clueRow: 1, clueCol: 5, row: 2, col: 5, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/prise" },
      { id: "F03-02", answer: "SALON", clue: "Pièce où la famille se réunit", cellClue: "Pièce pour se retrouver", definition: "Pièce de la maison où l’on s’assoit, discute et reçoit des invités.", lexicalLabel: "nom masculin", example: "Toute la famille regarde un film dans le salon.", direction: "across", clueRow: 5, clueCol: 4, row: 5, col: 5, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/salon" },
      { id: "F03-03", answer: "MAMAN", clue: "Mot familier pour parler de sa mère", cellClue: "Nom familier de la mère", definition: "Femme qui a un ou plusieurs enfants et prend soin d’eux au quotidien.", lexicalLabel: "nom féminin", example: "Maman prépare le dîner avec les enfants.", direction: "down", clueRow: 0, clueCol: 9, row: 1, col: 9, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/maman" },
      { id: "F03-04", answer: "PAPA", clue: "Mot familier pour parler de son père", cellClue: "Nom familier du père", definition: "Homme qui a un ou plusieurs enfants et prend soin d’eux au quotidien.", lexicalLabel: "nom masculin", example: "Papa aide son fils à ranger sa chambre.", direction: "down", clueRow: 0, clueCol: 2, row: 1, col: 2, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/papa" },
      { id: "F03-05", answer: "FILLE", clue: "Enfant ou jeune personne de sexe féminin", cellClue: "Jeune personne féminine", definition: "Jeune personne de sexe féminin, considérée aussi par rapport à ses parents.", lexicalLabel: "nom féminin", example: "La fille joue avec son frère dans le jardin.", direction: "across", clueRow: 8, clueCol: 4, row: 8, col: 5, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/fille" },
      { id: "F03-06", answer: "MUR", clue: "Surface verticale qui sépare les pièces", cellClue: "Sépare les pièces", definition: "Construction verticale solide qui limite un espace ou sépare deux pièces.", lexicalLabel: "nom masculin", example: "La famille accroche une photo au mur du couloir.", direction: "down", clueRow: 5, clueCol: 3, row: 6, col: 3, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/mur" },
      { id: "F03-07", answer: "LIT", clue: "Meuble où l’on dort", cellClue: "Meuble pour dormir", definition: "Meuble composé d’un cadre et d’un matelas, utilisé pour dormir et se reposer.", lexicalLabel: "nom masculin", example: "Le petit lit est placé près de la fenêtre.", direction: "down", clueRow: 6, clueCol: 6, row: 7, col: 6, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/lit" },
      { id: "F03-08", answer: "BOL", clue: "Petit récipient rond pour manger ou boire", cellClue: "Petit récipient rond", definition: "Récipient creux et arrondi servant à boire ou à manger certains aliments.", lexicalLabel: "nom masculin", example: "Le garçon verse du lait chaud dans son bol.", direction: "down", clueRow: 3, clueCol: 1, row: 4, col: 1, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/bol" },
      { id: "F03-09", answer: "BALAI", clue: "Objet utilisé pour nettoyer le sol", cellClue: "Sert à nettoyer le sol", definition: "Objet muni d’un long manche et de fibres, utilisé pour rassembler la poussière.", lexicalLabel: "nom masculin", example: "On passe le balai après le repas du soir.", direction: "across", clueRow: 4, clueCol: 0, row: 4, col: 1, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/balai" },
      { id: "F03-10", answer: "ONCLE", clue: "Frère du père ou de la mère", cellClue: "Frère d’un parent", definition: "Homme de la famille qui est le frère ou le beau-frère de l’un des parents.", lexicalLabel: "nom masculin", example: "Mon oncle habite à Fès et vient nous voir dimanche.", direction: "down", clueRow: 4, clueCol: 8, row: 5, col: 8, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/oncle" },
      { id: "F03-11", answer: "LAMPE", clue: "Objet qui donne de la lumière", cellClue: "Donne de la lumière", definition: "Appareil qui produit de la lumière pour éclairer une pièce ou un espace.", lexicalLabel: "nom féminin", example: "La lampe du bureau éclaire le cahier de Lina.", direction: "across", clueRow: 6, clueCol: 0, row: 6, col: 1, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/lampe" },
    ],
  },
  {
    id: "jet-encre-mf-facile-04",
    version: 1,
    rewardVersion: 1,
    levelId: "facile",
    level: "Facile",
    cefr: "A1",
    title: "Au marché du quartier",
    theme: "Aliments, contenants et gestes pour faire les courses",
    xp: 20,
    rows: 10,
    cols: 10,
    entries: [
      { id: "F04-01", answer: "HERBE", clue: "Petite plante verte qui pousse au sol", cellClue: "Petite plante verte", definition: "Plante basse aux tiges souples qui pousse dans les jardins, les champs ou les prés.", lexicalLabel: "nom féminin", example: "Cette herbe fraîche parfume la soupe du dîner.", direction: "across", clueRow: 5, clueCol: 1, row: 5, col: 2, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/herbe" },
      { id: "F04-02", answer: "BOIRE", clue: "Avaler un liquide", cellClue: "Avaler un liquide", definition: "Faire passer un liquide de la bouche vers l’estomac pour calmer sa soif.", lexicalLabel: "verbe", example: "Après le marché, nous allons boire un verre d’eau.", direction: "down", clueRow: 4, clueCol: 5, row: 5, col: 5, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/boire" },
      { id: "F04-03", answer: "OLIVE", clue: "Petit fruit vert ou noir dont on fait de l’huile", cellClue: "Petit fruit vert ou noir", definition: "Petit fruit charnu, vert puis noir, consommé seul ou utilisé pour produire une huile.", lexicalLabel: "nom féminin", example: "Le vendeur pèse des olives vertes pour la cliente.", direction: "across", clueRow: 9, clueCol: 0, row: 9, col: 1, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/olive" },
      { id: "F04-04", answer: "FÈVE", clue: "Graine verte cuisinée comme un légume", cellClue: "Graine verte à cuisiner", definition: "Grosse graine plate et verte que l’on mange fraîche, sèche ou cuite.", lexicalLabel: "nom féminin", example: "Ma grand-mère ajoute des fèves au plat du midi.", direction: "across", clueRow: 2, clueCol: 0, row: 2, col: 1, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/fève" },
      { id: "F04-05", answer: "SIROP", clue: "Liquide sucré à mélanger avec de l’eau", cellClue: "Liquide très sucré", definition: "Liquide épais et sucré, souvent parfumé, que l’on dilue pour préparer une boisson.", lexicalLabel: "nom masculin", example: "Le café vend un sirop de grenadine très frais.", direction: "down", clueRow: 4, clueCol: 8, row: 5, col: 8, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/sirop" },
      { id: "F04-06", answer: "SEL", clue: "Petits grains blancs qui donnent du goût", cellClue: "Grains blancs au goût salé", definition: "Substance blanche en petits grains utilisée en cuisine pour relever la saveur des plats.", lexicalLabel: "nom masculin", example: "Le cuisinier ajoute une pincée de sel à la soupe.", direction: "across", clueRow: 3, clueCol: 5, row: 3, col: 6, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/sel" },
      { id: "F04-07", answer: "RIZ", clue: "Petits grains blancs cuits dans l’eau", cellClue: "Grains blancs à cuire", definition: "Céréale formée de petits grains que l’on fait cuire avant de les manger.", lexicalLabel: "nom masculin", example: "Nous achetons un kilo de riz chez l’épicier.", direction: "across", clueRow: 6, clueCol: 6, row: 6, col: 7, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/riz" },
      { id: "F04-08", answer: "POT", clue: "Petit récipient pour une plante ou un aliment", cellClue: "Contient une plante ou du miel", definition: "Récipient généralement rond qui sert à conserver ou présenter un produit.", lexicalLabel: "nom masculin", example: "Le marchand ouvre un pot de miel pour le client.", direction: "across", clueRow: 1, clueCol: 3, row: 1, col: 4, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/pot" },
      { id: "F04-09", answer: "PESER", clue: "Mesurer le poids avec une balance", cellClue: "Mesurer avec une balance", definition: "Mesurer le poids d’un objet ou d’un aliment au moyen d’une balance.", lexicalLabel: "verbe", example: "La vendeuse va peser les légumes avant de donner le prix.", direction: "down", clueRow: 0, clueCol: 4, row: 1, col: 4, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/peser" },
      { id: "F04-10", answer: "RAYON", clue: "Partie d’un magasin où sont regroupés des produits", cellClue: "Espace de produits en magasin", definition: "Partie d’un magasin où des produits de même type sont présentés ensemble.", lexicalLabel: "nom masculin", example: "Le lait se trouve au rayon des boissons.", direction: "across", clueRow: 8, clueCol: 4, row: 8, col: 5, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/rayon" },
      { id: "F04-11", answer: "TASSE", clue: "Petit récipient avec une anse pour boire", cellClue: "Petit récipient avec une anse", definition: "Petit récipient muni d’une anse, utilisé pour servir une boisson chaude.", lexicalLabel: "nom féminin", example: "Le serveur pose une tasse de café sur la table.", direction: "down", clueRow: 0, clueCol: 6, row: 1, col: 6, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/tasse" },
    ],
  },
  {
    id: "jet-encre-mf-facile-05",
    version: 1,
    rewardVersion: 1,
    levelId: "facile",
    level: "Facile",
    cefr: "A1",
    title: "En ville et en chemin",
    theme: "Lieux, transports et repères du quartier",
    xp: 20,
    rows: 10,
    cols: 10,
    entries: [
      { id: "F05-01", answer: "ENTRE", clue: "Va de l’extérieur vers l’intérieur", cellClue: "Va à l’intérieur", definition: "Passe d’un endroit extérieur à l’intérieur d’un lieu.", lexicalLabel: "verbe", example: "Le bus entre dans la ville par la route principale.", direction: "down", clueRow: 1, clueCol: 5, row: 2, col: 5, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/entrer" },
      { id: "F05-02", answer: "ROUTE", clue: "Voie où circulent les voitures", cellClue: "Voie pour les voitures", definition: "Voie aménagée qui relie des lieux et permet la circulation des véhicules.", lexicalLabel: "nom féminin", example: "La route entre Rabat et Salé est très fréquentée.", direction: "across", clueRow: 5, clueCol: 4, row: 5, col: 5, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/route" },
      { id: "F05-03", answer: "VILLE", clue: "Grand lieu habité avec des rues et des quartiers", cellClue: "Lieu avec rues et quartiers", definition: "Espace habité important qui rassemble des maisons, des services et de nombreuses rues.", lexicalLabel: "nom féminin", example: "Casablanca est une grande ville du Maroc.", direction: "down", clueRow: 0, clueCol: 9, row: 1, col: 9, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/ville" },
      { id: "F05-04", answer: "TOUR", clue: "Bâtiment très haut et étroit", cellClue: "Bâtiment très haut", definition: "Construction beaucoup plus haute que large, souvent visible de loin dans une ville.", lexicalLabel: "nom féminin", example: "Une grande tour domine les immeubles du quartier.", direction: "down", clueRow: 0, clueCol: 2, row: 1, col: 2, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/tour" },
      { id: "F05-05", answer: "RADIO", clue: "Appareil qui diffuse musique et informations", cellClue: "Diffuse musique et informations", definition: "Appareil qui reçoit des émissions sonores pour écouter des nouvelles ou de la musique.", lexicalLabel: "nom féminin", example: "Le chauffeur écoute la radio pendant le trajet.", direction: "across", clueRow: 8, clueCol: 4, row: 8, col: 5, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/radio" },
      { id: "F05-06", answer: "AIR", clue: "Ce que nous respirons", cellClue: "Ce que nous respirons", definition: "Mélange invisible de gaz qui entoure la Terre et permet aux êtres vivants de respirer.", lexicalLabel: "nom masculin", example: "Dans le parc, l’air semble plus frais qu’au centre-ville.", direction: "down", clueRow: 5, clueCol: 3, row: 6, col: 3, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/air" },
      { id: "F05-07", answer: "CAR", clue: "Grand véhicule pour voyager sur la route", cellClue: "Grand véhicule pour voyager", definition: "Véhicule routier qui transporte un groupe de passagers sur une longue distance.", lexicalLabel: "nom masculin", example: "Le car relie le village à la ville chaque matin.", direction: "down", clueRow: 6, clueCol: 6, row: 7, col: 6, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/car" },
      { id: "F05-08", answer: "BUS", clue: "Grand véhicule qui transporte plusieurs personnes", cellClue: "Transport collectif", definition: "Grand véhicule routier qui transporte de nombreux passagers sur un trajet régulier.", lexicalLabel: "nom masculin", example: "Le bus s’arrête près du marché à huit heures.", direction: "down", clueRow: 3, clueCol: 1, row: 4, col: 1, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/bus" },
      { id: "F05-09", answer: "BRUIT", clue: "Son fort ou gênant que l’on entend", cellClue: "Son fort ou gênant", definition: "Son que l’on entend et qui peut devenir désagréable lorsqu’il est trop fort.", lexicalLabel: "nom masculin", example: "Le bruit des voitures diminue après la pluie.", direction: "across", clueRow: 4, clueCol: 0, row: 4, col: 1, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/bruit" },
      { id: "F05-10", answer: "TRAIN", clue: "Long véhicule qui roule sur des rails", cellClue: "Roule sur des rails", definition: "Moyen de transport composé de plusieurs voitures et guidé par une voie ferrée.", lexicalLabel: "nom masculin", example: "Le train part de la gare de Rabat à neuf heures.", direction: "down", clueRow: 4, clueCol: 8, row: 5, col: 8, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/train" },
      { id: "F05-11", answer: "STADE", clue: "Grand lieu où l’on pratique un sport", cellClue: "Lieu pour les matchs", definition: "Grande installation avec un terrain et des places pour les spectateurs.", lexicalLabel: "nom masculin", example: "La famille va au stade pour regarder le match.", direction: "across", clueRow: 6, clueCol: 0, row: 6, col: 1, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/stade" },
    ],
  },
  {
    id: "jet-encre-mf-facile-06",
    version: 1,
    rewardVersion: 1,
    levelId: "facile",
    level: "Facile",
    cefr: "A1",
    title: "Paysages du Maroc",
    theme: "Relief, eau, animaux et nature du pays",
    xp: 20,
    rows: 10,
    cols: 10,
    entries: [
      { id: "F06-01", answer: "VENTS", clue: "Mouvements d’air que l’on sent dehors", cellClue: "Mouvements de l’air", definition: "Déplacements naturels de l’air, parfois doux et parfois forts.", lexicalLabel: "nom masculin pluriel", example: "Les vents déplacent le sable près des dunes.", direction: "across", clueRow: 5, clueCol: 1, row: 5, col: 2, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/vent" },
      { id: "F06-02", answer: "TERRE", clue: "Sol naturel où poussent les plantes", cellClue: "Sol où poussent les plantes", definition: "Matière brune ou rouge du sol dans laquelle les végétaux peuvent prendre racine.", lexicalLabel: "nom féminin", example: "Le jardinier plante l’arbre dans une terre humide.", direction: "down", clueRow: 4, clueCol: 5, row: 5, col: 5, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/terre" },
      { id: "F06-03", answer: "PLAGE", clue: "Bord de mer couvert de sable", cellClue: "Bord de mer avec du sable", definition: "Étendue située au bord de la mer, souvent couverte de sable ou de petits galets.", lexicalLabel: "nom féminin", example: "La famille marche sur la plage d’Essaouira.", direction: "across", clueRow: 9, clueCol: 0, row: 9, col: 1, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/plage" },
      { id: "F06-04", answer: "TUBA", clue: "Tube qui permet de respirer près de la surface", cellClue: "Tube pour respirer dans l’eau", definition: "Tube courbé que le nageur garde en bouche pour respirer près de la surface.", lexicalLabel: "nom masculin", example: "Le nageur utilise un tuba dans l’eau calme de la baie.", direction: "across", clueRow: 2, clueCol: 0, row: 2, col: 1, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/tuba" },
      { id: "F06-05", answer: "VACHE", clue: "Grand animal de ferme qui donne du lait", cellClue: "Animal qui donne du lait", definition: "Grand animal femelle élevé dans les fermes pour son lait et parfois sa viande.", lexicalLabel: "nom féminin", example: "La vache mange de l’herbe près de la ferme.", direction: "down", clueRow: 4, clueCol: 8, row: 5, col: 8, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/vache" },
      { id: "F06-06", answer: "NID", clue: "Abri construit par un oiseau", cellClue: "Abri d’un oiseau", definition: "Petit logement fait de brindilles où un oiseau pond ses œufs et protège ses petits.", lexicalLabel: "nom masculin", example: "Un oiseau prépare son nid dans le palmier.", direction: "across", clueRow: 3, clueCol: 5, row: 3, col: 6, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/nid" },
      { id: "F06-07", answer: "LAC", clue: "Grande étendue d’eau entourée de terre", cellClue: "Étendue d’eau entourée de terre", definition: "Étendue d’eau située à l’intérieur des terres et entourée de rives.", lexicalLabel: "nom masculin", example: "Le lac reflète les montagnes sous le ciel bleu.", direction: "across", clueRow: 6, clueCol: 6, row: 6, col: 7, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/lac" },
      { id: "F06-08", answer: "SUD", clue: "Direction opposée au nord", cellClue: "Direction opposée au nord", definition: "L’un des quatre points cardinaux, placé à l’opposé du nord sur une carte.", lexicalLabel: "nom masculin", example: "Agadir se trouve dans le sud-ouest du Maroc.", direction: "across", clueRow: 1, clueCol: 3, row: 1, col: 4, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/sud" },
      { id: "F06-09", answer: "SAPIN", clue: "Arbre vert portant des aiguilles", cellClue: "Arbre vert à aiguilles", definition: "Grand arbre résineux dont les feuilles fines restent vertes toute l’année.", lexicalLabel: "nom masculin", example: "Un sapin pousse sur le versant frais de la montagne.", direction: "down", clueRow: 0, clueCol: 4, row: 1, col: 4, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/sapin" },
      { id: "F06-10", answer: "ROCHE", clue: "Matière dure qui forme les montagnes", cellClue: "Matière dure des montagnes", definition: "Matière minérale très solide présente dans le sol, les falaises et les montagnes.", lexicalLabel: "nom féminin", example: "Une grande roche borde le chemin de randonnée.", direction: "across", clueRow: 8, clueCol: 4, row: 8, col: 5, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/roche" },
      { id: "F06-11", answer: "DUNES", clue: "Collines de sable formées par le vent", cellClue: "Collines de sable", definition: "Reliefs arrondis créés lorsque le vent déplace et accumule beaucoup de sable.", lexicalLabel: "nom féminin pluriel", example: "Les dunes de Merzouga changent de forme avec le vent.", direction: "down", clueRow: 0, clueCol: 6, row: 1, col: 6, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/dune" },
    ],
  },
]);
