const ENTRY_LAYOUTS = Object.freeze([
  Object.freeze({ direction: "across", clueRow: 6, clueCol: 0, row: 6, col: 1 }),
  Object.freeze({ direction: "down", clueRow: 4, clueCol: 1, row: 5, col: 1 }),
  Object.freeze({ direction: "down", clueRow: 3, clueCol: 4, row: 4, col: 4 }),
  Object.freeze({ direction: "down", clueRow: 5, clueCol: 7, row: 6, col: 7 }),
  Object.freeze({ direction: "down", clueRow: 0, clueCol: 10, row: 1, col: 10 }),
  Object.freeze({ direction: "across", clueRow: 2, clueCol: 5, row: 2, col: 6 }),
  Object.freeze({ direction: "across", clueRow: 4, clueCol: 2, row: 4, col: 3 }),
  Object.freeze({ direction: "across", clueRow: 8, clueCol: 2, row: 8, col: 3 }),
  Object.freeze({ direction: "down", clueRow: 7, clueCol: 6, row: 8, col: 6 }),
  Object.freeze({ direction: "across", clueRow: 12, clueCol: 2, row: 12, col: 3 }),
  Object.freeze({ direction: "across", clueRow: 10, clueCol: 5, row: 10, col: 6 }),
  Object.freeze({ direction: "down", clueRow: 7, clueCol: 10, row: 8, col: 10 }),
  Object.freeze({ direction: "down", clueRow: 4, clueCol: 12, row: 5, col: 12 }),
]);

function defineGrid({ code, ...grid }, entries) {
  return Object.freeze({
    ...grid,
    entries: Object.freeze(entries.map((entry, index) => Object.freeze({
      id: `${code}-${String(index + 1).padStart(2, "0")}`,
      ...entry,
      ...ENTRY_LAYOUTS[index],
    }))),
  });
}

export const EXTRA_DIFFICILE_GRIDS = Object.freeze([
  defineGrid({
    code: "D02",
    id: "jet-encre-mf-difficile-02",
    version: 1,
    rewardVersion: 1,
    levelId: "difficile",
    level: "Difficile",
    cefr: "A2–B1",
    title: "Le laboratoire des sciences",
    theme: "Matière, observation, mesures et phénomènes scientifiques",
    xp: 50,
    rows: 13,
    cols: 13,
  }, [
    { answer: "PHYSICIENS", clue: "Spécialistes de la matière et de l’énergie", cellClue: "Étudient la matière", definition: "Scientifiques qui observent et décrivent les lois de la matière et de l’énergie.", lexicalLabel: "nom pluriel — sciences", example: "Les physiciens mesurent le mouvement du chariot.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/physicien" },
    { answer: "SPHÈRE", clue: "Surface d’une boule", cellClue: "Surface de boule", definition: "Surface d’une boule : tous ses points sont à la même distance de son centre.", lexicalLabel: "nom féminin — géométrie", example: "La surface d’une balle a la forme d’une sphère.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/sphere" },
    { answer: "PISTONS", clue: "Pièces mobiles dans certains moteurs", cellClue: "Pièces mobiles d’un moteur", definition: "Pièces cylindriques qui se déplacent dans un moteur ou une pompe.", lexicalLabel: "nom pluriel — mécanique", example: "Les pistons montent et descendent dans le moteur.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/piston" },
    { answer: "ION", clue: "Atome ou groupe d’atomes portant une charge électrique", cellClue: "Particule chargée", definition: "Particule chargée électriquement, formée par un atome ou par un groupe d’atomes.", lexicalLabel: "nom masculin — sciences", example: "Cet ion possède une charge électrique positive.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/ion" },
    { answer: "ASTRES", clue: "Corps naturels visibles dans l’espace", cellClue: "Corps célestes", definition: "Corps célestes tels que les planètes, les satellites ou les étoiles.", lexicalLabel: "nom pluriel — astronomie", example: "Les astres semblent se déplacer dans le ciel nocturne.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/astre" },
    { answer: "OSMOSE", clue: "Passage de l’eau à travers une membrane", cellClue: "Eau via une membrane", definition: "Passage de l’eau à travers une membrane sélective, du milieu le moins concentré en solutés vers le plus concentré.", lexicalLabel: "nom féminin — sciences", example: "L’osmose fait entrer de l’eau dans certaines cellules.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/osmose" },
    { answer: "OPALE", clue: "Pierre fine aux reflets changeants", cellClue: "Pierre aux reflets changeants", definition: "Minéral riche en silice dont la surface peut montrer plusieurs couleurs.", lexicalLabel: "nom féminin — minéralogie", example: "L’opale observée présente des reflets verts et bleus.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/opale" },
    { answer: "BOBINE", clue: "Fil conducteur enroulé en plusieurs tours", cellClue: "Fil enroulé", definition: "Enroulement de fil qui crée un champ magnétique quand le courant passe.", lexicalLabel: "nom féminin — électricité", example: "Quand le courant passe, la bobine attire un petit clou en fer.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/bobine" },
    { answer: "IMAGE", clue: "Représentation obtenue ou observée", cellClue: "Photo ou dessin", definition: "Reproduction visuelle d’un objet, d’une personne ou d’un phénomène.", lexicalLabel: "nom féminin", example: "Le microscope affiche une image agrandie de la cellule.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/image" },
    { answer: "LASER", clue: "Appareil qui produit un faisceau lumineux très étroit", cellClue: "Produit un faisceau lumineux", definition: "Appareil qui produit un faisceau lumineux très étroit et dirigé.", lexicalLabel: "nom masculin — physique", example: "Le laboratoire utilise un laser de faible puissance.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/laser" },
    { answer: "AMPÈRES", clue: "Unités de l’intensité électrique", cellClue: "Unités d’intensité", definition: "Unités utilisées pour exprimer l’intensité d’un courant électrique.", lexicalLabel: "nom pluriel — physique", example: "L’appareil indique deux ampères sur son écran.", sourceLabel: "BIPM", sourceUrl: "https://www.bipm.org/fr/measurement-units" },
    { answer: "FORCE", clue: "Action capable de modifier un mouvement", cellClue: "Action qui modifie un mouvement", definition: "Action mécanique pouvant accélérer, ralentir ou déformer un corps.", lexicalLabel: "nom féminin — physique", example: "Une force pousse le chariot vers l’avant.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/force" },
    { answer: "VITESSES", clue: "Rapports entre distances et durées", cellClue: "Allures", definition: "Grandeurs qui indiquent la distance parcourue pendant une durée donnée.", lexicalLabel: "nom féminin pluriel — physique", example: "Les deux voitures roulent à des vitesses différentes.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/vitesse" },
  ]),
  defineGrid({
    code: "D03",
    id: "jet-encre-mf-difficile-03",
    version: 1,
    rewardVersion: 1,
    levelId: "difficile",
    level: "Difficile",
    cefr: "A2–B1",
    title: "Citoyens en action",
    theme: "Vie collective, participation, services publics et solidarité",
    xp: 50,
    rows: 13,
    cols: 13,
  }, [
    { answer: "SOLIDARITÉ", clue: "Entraide entre les membres d’un groupe", cellClue: "Entraide", definition: "Lien qui pousse des personnes à se soutenir et à agir les unes pour les autres.", lexicalLabel: "nom féminin — citoyenneté", example: "La solidarité aide les familles après les fortes pluies.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/solidarite" },
    { answer: "ESPRIT", clue: "Manière de penser et de comprendre", cellClue: "Manière de penser", definition: "Ensemble des idées et des attitudes qui guident une personne ou un groupe.", lexicalLabel: "nom masculin", example: "L’esprit d’équipe facilite le travail de la classe.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/esprit" },
    { answer: "OPINION", clue: "Avis personnel sur une question", cellClue: "Point de vue", definition: "Jugement qu’une personne formule à propos d’un sujet ou d’une situation.", lexicalLabel: "nom féminin", example: "Chaque élève explique son opinion sans interrompre les autres.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/opinion" },
    { answer: "RUE", clue: "Voie publique entre des bâtiments", cellClue: "Voie en ville", definition: "Espace de circulation aménagé dans une ville et accessible à tous.", lexicalLabel: "nom féminin", example: "Les habitants gardent leur rue propre et accueillante.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/rue" },
    { answer: "LIBÉRÉ", clue: "Qui n’est plus retenu ni enfermé", cellClue: "Délivré", definition: "Qui n’est plus retenu, enfermé ou soumis à une contrainte.", lexicalLabel: "adjectif masculin", example: "L’oiseau soigné est libéré près de la forêt.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/liberer" },
    { answer: "PUBLIC", clue: "Qui concerne toute la collectivité", cellClue: "Pour toute la collectivité", definition: "Qui appartient à la communauté ou reste accessible à l’ensemble des citoyens.", lexicalLabel: "adjectif masculin", example: "Le jardin public accueille les familles du quartier.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/public" },
    { answer: "VOTER", clue: "Exprimer son choix lors d’une décision", cellClue: "Exprimer son choix", definition: "Exprimer son choix lors d’une décision collective, par exemple en déposant un bulletin ou en levant la main.", lexicalLabel: "verbe", example: "Les délégués vont voter pour choisir le projet de classe.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/voter" },
    { answer: "LIBRES", clue: "Sans contrainte injuste", cellClue: "Sans entrave", definition: "Qui peuvent décider ou agir dans le respect des droits et des lois.", lexicalLabel: "adjectif pluriel", example: "Les citoyens sont libres d’exprimer un avis respectueux.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/libre" },
    { answer: "RÉUNI", clue: "Rassemblé avec d’autres personnes", cellClue: "Groupé", definition: "Qui se trouve avec plusieurs personnes dans un même lieu ou autour d’un projet.", lexicalLabel: "adjectif masculin", example: "Le conseil est réuni pour discuter du nouveau règlement.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/reunir" },
    { answer: "CIVIL", clue: "Relatif aux citoyens et à leur vie commune", cellClue: "Relatif aux citoyens", definition: "Qui concerne les personnes, leurs droits et les relations ordinaires dans la société.", lexicalLabel: "adjectif masculin", example: "L’état civil enregistre les naissances et les mariages.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/civil" },
    { answer: "USAGERS", clue: "Personnes qui utilisent un service", cellClue: "Utilisent un service", definition: "Personnes qui fréquentent un équipement ou bénéficient d’un service collectif.", lexicalLabel: "nom masculin pluriel", example: "Les usagers proposent des améliorations pour la bibliothèque.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/usager" },
    { answer: "AGENT", clue: "Personne chargée d’une mission", cellClue: "En mission", definition: "Personne qui exerce une fonction précise pour une organisation ou un service.", lexicalLabel: "nom masculin", example: "Un agent municipal renseigne les habitants à l’accueil.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/agent" },
    { answer: "RÉPONSES", clue: "Informations données après des questions", cellClue: "Après une question", definition: "Informations formulées pour expliquer, confirmer ou résoudre ce qui a été demandé.", lexicalLabel: "nom féminin pluriel", example: "Les réponses du conseil seront affichées demain.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/reponse" },
  ]),
  defineGrid({
    code: "D04",
    id: "jet-encre-mf-difficile-04",
    version: 1,
    rewardVersion: 1,
    levelId: "difficile",
    level: "Difficile",
    cefr: "A2–B1",
    title: "Équilibres de la planète",
    theme: "Milieux naturels, météo, ressources et gestes écologiques",
    xp: 50,
    rows: 13,
    cols: 13,
  }, [
    { answer: "RECYCLAGES", clue: "Transformations de déchets en ressources", cellClue: "Nouvelles vies des déchets", definition: "Opérations qui permettent de traiter des matériaux usagés pour les réutiliser.", lexicalLabel: "nom masculin pluriel", example: "Les recyclages du papier et du verre économisent des ressources.", sourceLabel: "ADEME", sourceUrl: "https://agirpourlatransition.ademe.fr/particuliers/maison/dechets" },
    { answer: "ARIDES", clue: "Très secs et pauvres en eau", cellClue: "Très secs", definition: "Qui reçoivent très peu de pluie et manquent durablement d’humidité.", lexicalLabel: "adjectif pluriel", example: "Les milieux arides abritent des espèces adaptées au manque d’eau.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/aride" },
    { answer: "PAYSAGE", clue: "Étendue visible depuis un lieu", cellClue: "Étendue visible", definition: "Ensemble formé par le relief, la végétation et les aménagements observables.", lexicalLabel: "nom masculin — géographie", example: "Le paysage change entre la côte et les montagnes.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/paysage" },
    { answer: "AXE", clue: "Ligne principale servant de repère", cellClue: "Ligne repère", definition: "Direction de référence utilisée pour organiser un espace ou un déplacement.", lexicalLabel: "nom masculin", example: "Cet axe routier relie le village à la ville voisine.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/axe" },
    { answer: "PLUIES", clue: "Précipitations d’eau venant des nuages", cellClue: "Averses", definition: "Précipitations liquides qui apportent de l’eau aux sols et aux végétaux.", lexicalLabel: "nom féminin pluriel", example: "Les pluies d’automne remplissent peu à peu les barrages.", sourceLabel: "Météo-France", sourceUrl: "https://meteofrance.com/comprendre-la-meteo/precipitations" },
    { answer: "JUNGLE", clue: "Forêt tropicale très dense", cellClue: "Forêt dense", definition: "Milieu chaud et humide où la végétation pousse de façon très abondante.", lexicalLabel: "nom féminin — géographie", example: "La jungle abrite une grande diversité d’animaux et de plantes.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/jungle" },
    { answer: "ÉPINE", clue: "Pointe dure portée par certaines plantes", cellClue: "Pointe végétale", definition: "Partie rigide et piquante qui protège la tige ou les branches de certains végétaux.", lexicalLabel: "nom féminin — botanique", example: "Une épine protège la branche contre certains animaux.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/epine" },
    { answer: "DANGER", clue: "Situation pouvant causer un dommage", cellClue: "Risque de subir un dommage", definition: "Menace susceptible de blesser un être vivant ou de dégrader un milieu.", lexicalLabel: "nom masculin", example: "La fumée signale un danger pour les habitants et la forêt.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/danger" },
    { answer: "GALET", clue: "Pierre arrondie par l’eau", cellClue: "Pierre arrondie", definition: "Petit morceau de roche lisse, façonné par les vagues ou le courant.", lexicalLabel: "nom masculin — géologie", example: "L’enfant observe un galet poli sur la plage d’Essaouira.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/galet" },
    { answer: "VENTS", clue: "Déplacements naturels de l’air", cellClue: "Souffles d’air", definition: "Mouvements de l’atmosphère allant d’une zone de pression vers une autre.", lexicalLabel: "nom masculin pluriel", example: "Les vents forts déplacent le sable près de la côte.", sourceLabel: "Météo-France", sourceUrl: "https://meteofrance.com/comprendre-la-meteo/le-vent" },
    { answer: "LAGUNES", clue: "Étendues d’eau séparées de la mer", cellClue: "Plans d’eau côtiers peu profonds", definition: "Plans d’eau côtiers peu profonds, isolés du large par une bande de terre.", lexicalLabel: "nom pluriel — géographie", example: "Les lagunes servent de refuge à de nombreux oiseaux migrateurs.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/lagune" },
    { answer: "DUNES", clue: "Collines de sable formées par le vent", cellClue: "Collines de sable", definition: "Collines de sable formées par le vent, dans les déserts ou sur les côtes.", lexicalLabel: "nom pluriel — géographie", example: "Les dunes changent lentement de forme sous l’action du vent.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/dune" },
    { answer: "BIOMASSE", clue: "Masse totale de matière organique dans un milieu", cellClue: "Masse de matière organique", definition: "Quantité de matière organique issue des êtres vivants dans un milieu donné.", lexicalLabel: "nom féminin — écologie", example: "La biomasse végétale peut servir à produire de l’énergie.", sourceLabel: "ADEME", sourceUrl: "https://agirpourlatransition.ademe.fr/particuliers/maison/energies/biomasse" },
  ]),
  defineGrid({
    code: "D05",
    id: "jet-encre-mf-difficile-05",
    version: 1,
    rewardVersion: 1,
    levelId: "difficile",
    level: "Difficile",
    cefr: "A2–B1",
    title: "Patrimoine en partage",
    theme: "Langue, arts, habits et traditions du Maroc et du monde",
    xp: 50,
    rows: 13,
    cols: 13,
  }, [
    { answer: "PATRIMOINE", clue: "Biens transmis par les générations", cellClue: "Biens transmis", definition: "Ensemble de lieux, d’objets et de pratiques hérités que la société souhaite conserver.", lexicalLabel: "nom masculin — culture", example: "Les élèves découvrent le patrimoine de leur région.", sourceLabel: "UNESCO", sourceUrl: "https://whc.unesco.org/fr/etatsparties/ma" },
    { answer: "ÉPOQUE", clue: "Période marquée par des événements", cellClue: "Période de l’histoire", definition: "Portion du temps historique caractérisée par des faits et des modes de vie particuliers.", lexicalLabel: "nom féminin — histoire", example: "Ce manuscrit date d’une époque ancienne.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/epoque" },
    { answer: "CARTONS", clue: "Supports épais utilisés pour dessiner", cellClue: "Supports épais pour le dessin", definition: "Feuilles rigides servant de base à des œuvres, des maquettes ou des affiches.", lexicalLabel: "nom masculin pluriel — arts", example: "Les élèves découpent des cartons pour préparer une maquette.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/carton" },
    { answer: "OUI", clue: "Mot qui exprime l’accord", cellClue: "Exprime l’accord", definition: "Réponse affirmative employée pour accepter, confirmer ou approuver une proposition.", lexicalLabel: "adverbe", example: "Elle répond oui à l’invitation du club de lecture.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/oui" },
    { answer: "LANGUE", clue: "Système de mots partagé par un groupe", cellClue: "Langage commun", definition: "Ensemble de signes et de règles permettant aux membres d’une communauté de communiquer.", lexicalLabel: "nom féminin — linguistique", example: "La langue française se pratique aussi par le théâtre.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/langue" },
    { answer: "CAFTAN", clue: "Long vêtement d’apparat marocain", cellClue: "Vêtement d’apparat marocain", definition: "Robe longue et élégante, souvent brodée, portée lors de fêtes et de cérémonies.", lexicalLabel: "nom masculin — vêtement", example: "Le caftan présenté au musée possède de fines broderies.", sourceLabel: "Office National Marocain du Tourisme", sourceUrl: "https://www.visitmorocco.com/fr/decouvrir-le-maroc/artisanat" },
    { answer: "SCÈNE", clue: "Espace où jouent les artistes", cellClue: "Plateau de théâtre", definition: "Partie d’une salle destinée aux représentations de théâtre, de danse ou de musique.", lexicalLabel: "nom féminin — spectacle", example: "Les comédiens entrent en scène devant les familles.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/scene" },
    { answer: "POÉSIE", clue: "Art qui travaille le rythme des mots", cellClue: "Art des vers", definition: "Création littéraire qui joue sur les sons, les images et le rythme du langage.", lexicalLabel: "nom féminin — littérature", example: "La poésie permet aux élèves d’exprimer leurs émotions.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/poesie" },
    { answer: "SALON", clue: "Exposition consacrée à un domaine, par exemple aux livres", cellClue: "Exposition spécialisée", definition: "Manifestation où l’on présente au public des livres, des œuvres ou des produits autour d’un thème commun.", lexicalLabel: "nom masculin", example: "Le salon du livre accueille des auteurs marocains.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/salon" },
    { answer: "CHANT", clue: "Suite de sons produite avec la voix", cellClue: "Mélodie produite par la voix", definition: "Production vocale organisée selon un rythme et des hauteurs musicales.", lexicalLabel: "nom masculin — musique", example: "Le chant traditionnel accompagne la fête du village.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/chant" },
    { answer: "LETTRES", clue: "Signes utilisés pour écrire les mots", cellClue: "Signes de l’écriture", definition: "Symboles d’un alphabet qui servent à noter les sons et à former des mots.", lexicalLabel: "nom féminin pluriel", example: "Les lettres arabes et latines ont des formes différentes.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/lettre" },
    { answer: "ÉCRIT", clue: "Message conservé sous forme de texte", cellClue: "Message sous forme de texte", definition: "Document composé de signes graphiques pour transmettre durablement une idée.", lexicalLabel: "nom masculin", example: "Chaque groupe prépare un écrit pour présenter son œuvre.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/ecrit" },
    { answer: "FANTASIA", clue: "Spectacle équestre traditionnel marocain", cellClue: "Spectacle équestre marocain", definition: "Démonstration collective de cavaliers comprenant une course et un tir coordonné.", lexicalLabel: "nom féminin — tradition", example: "La fantasia réunit des cavaliers en tenue traditionnelle.", sourceLabel: "UNESCO", sourceUrl: "https://ich.unesco.org/fr/RL/la-tbourida-01483" },
  ]),
  defineGrid({
    code: "D06",
    id: "jet-encre-mf-difficile-06",
    version: 1,
    rewardVersion: 1,
    levelId: "difficile",
    level: "Difficile",
    cefr: "A2–B1",
    title: "Médias et territoires",
    theme: "Information, image, ville, déplacements et repères géographiques",
    xp: 50,
    rows: 13,
    cols: 13,
  }, [
    { answer: "TÉLÉVISION", clue: "Média qui diffuse des images et des sons", cellClue: "Diffuse des images et des sons", definition: "Système de transmission de programmes audiovisuels vers des écrans.", lexicalLabel: "nom féminin — médias", example: "La télévision diffuse un reportage sur les villes marocaines.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/television" },
    { answer: "STUDIO", clue: "Lieu équipé pour enregistrer", cellClue: "Salle de radio", definition: "Local aménagé pour produire du son, des images ou une émission.", lexicalLabel: "nom masculin — médias", example: "Les élèves visitent un studio de radio à Casablanca.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/studio" },
    { answer: "CRÉDITS", clue: "Liste des personnes ayant participé à une œuvre", cellClue: "Noms liés à une production", definition: "Liste qui identifie les personnes et organismes ayant participé à une production.", lexicalLabel: "nom masculin pluriel — médias", example: "Les crédits apparaissent à la fin du documentaire.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/credit" },
    { answer: "SON", clue: "Vibration perçue par l’oreille", cellClue: "Vibration audible", definition: "Phénomène produit par des vibrations qui se propagent dans un milieu.", lexicalLabel: "nom masculin — acoustique", example: "Le technicien règle le son avant l’enregistrement.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/son" },
    { answer: "URBAIN", clue: "Qui appartient à la ville", cellClue: "Relatif à la ville", definition: "Qui concerne les espaces bâtis, les activités et les habitants des villes.", lexicalLabel: "adjectif masculin — géographie", example: "Le transport urbain relie plusieurs quartiers de Rabat.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/urbain" },
    { answer: "CAMÉRA", clue: "Appareil qui enregistre des images", cellClue: "Pour filmer", definition: "Appareil optique utilisé pour filmer une scène ou transmettre une vidéo.", lexicalLabel: "nom féminin — médias", example: "La caméra suit le journaliste dans les ruelles de la médina.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/camera" },
    { answer: "ICÔNE", clue: "Petit symbole affiché sur un écran", cellClue: "Symbole à l’écran", definition: "Signe graphique représentant une fonction, un fichier, un lieu ou une idée.", lexicalLabel: "nom féminin — numérique", example: "Clique sur l’icône pour ouvrir la carte interactive.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/icone" },
    { answer: "BILANS", clue: "Synthèses des résultats obtenus", cellClue: "États des lieux", definition: "Documents qui résument une situation, des actions ou des données à une date donnée.", lexicalLabel: "nom masculin pluriel", example: "Les bilans présentent les résultats de l’enquête locale.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/bilan" },
    { answer: "AVION", clue: "Moyen de transport aérien", cellClue: "Appareil de transport aérien", definition: "Appareil muni d’ailes qui transporte des personnes ou des marchandises dans les airs.", lexicalLabel: "nom masculin — transport", example: "L’avion relie Tanger à plusieurs villes européennes.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/avion" },
    { answer: "LIGNE", clue: "Tracé reliant plusieurs points", cellClue: "Trait continu", definition: "Suite continue de points servant de limite, de trajet ou de repère sur une carte.", lexicalLabel: "nom féminin — géographie", example: "Une ligne bleue représente le fleuve sur la carte.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/ligne" },
    { answer: "INDICES", clue: "Éléments qui aident à comprendre", cellClue: "Signes utiles", definition: "Signes ou informations permettant de retrouver une réponse ou d’établir un fait.", lexicalLabel: "nom masculin pluriel", example: "Le lecteur repère des indices dans le titre et la photographie.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/indice" },
    { answer: "LOCAL", clue: "Qui concerne un lieu proche", cellClue: "Du coin", definition: "Qui se rapporte à un territoire limité, une ville ou un voisinage précis.", lexicalLabel: "adjectif masculin", example: "Le journal local annonce les événements de la semaine.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/local" },
    { answer: "ADRESSES", clue: "Indications permettant de trouver un lieu", cellClue: "Indiquent où trouver un lieu", definition: "Indications précises, comme le nom d’une rue, un numéro et une localité, qui permettent de trouver un lieu.", lexicalLabel: "nom féminin pluriel", example: "Les adresses sont vérifiées avant de préparer l’itinéraire.", sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/adresse" },
  ]),
]);
