import { EXTRA_DIFFICILE_GRIDS } from "./motsFlechesExtraDifficile.js";
import { EXTRA_FACILE_GRIDS } from "./motsFlechesExtraFacile.js";
import { EXTRA_NORMAL_GRIDS } from "./motsFlechesExtraNormal.js";

const ORIGINAL_MOTS_FLECHES_GRIDS = Object.freeze([
  {
    id: "jet-encre-mf-facile-01",
    version: 3,
    rewardVersion: 1,
    levelId: "facile",
    level: "Facile",
    cefr: "A1",
    title: "À l’école et au quotidien",
    theme: "Objets, lieux et relations du quotidien",
    xp: 20,
    rows: 10,
    cols: 10,
    entries: [
      { id: "F01", answer: "ÉCOLE", clue: "Lieu où les élèves vont pour apprendre", cellClue: "Lieu où étudient les élèves", definition: "Lieu où des élèves apprennent avec des enseignants.", lexicalLabel: "nom féminin", example: "L’école ouvre ses portes à huit heures.", direction: "across", clueRow: 5, clueCol: 1, row: 5, col: 2, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9E0279" },
      { id: "F02", answer: "LIVRE", clue: "Pages reliées que l’on lit", cellClue: "Pages reliées que l’on lit", definition: "Objet fait de pages reliées, avec du texte ou des images.", lexicalLabel: "nom masculin", example: "Je lis un livre à la bibliothèque.", direction: "down", clueRow: 4, clueCol: 5, row: 5, col: 5, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9L1074" },
      { id: "F03", answer: "POMME", clue: "Fruit rond, rouge, vert ou jaune", cellClue: "Fruit rond, rouge ou vert", definition: "Fruit rond à la peau rouge, verte ou jaune, que l’on peut croquer.", lexicalLabel: "nom féminin", example: "Je mange une pomme au goûter.", direction: "across", clueRow: 9, clueCol: 0, row: 9, col: 1, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9P3311" },
      { id: "F04", answer: "CHAT", clue: "Animal qui miaule", cellClue: "Animal qui miaule", definition: "Petit animal domestique qui miaule.", lexicalLabel: "nom masculin", example: "Le chat dort près de la fenêtre.", direction: "across", clueRow: 2, clueCol: 0, row: 2, col: 1, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/chat" },
      { id: "F05", answer: "TABLE", clue: "Meuble où l’on pose les assiettes pour manger", cellClue: "Meuble où l’on mange", definition: "Meuble avec un plateau, utilisé pour manger, écrire ou travailler.", lexicalLabel: "nom féminin", example: "Nous posons les cahiers sur la table.", direction: "down", clueRow: 4, clueCol: 8, row: 5, col: 8, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9T0028" },
      { id: "F06", answer: "AMI", clue: "Personne que l’on aime bien et avec qui l’on joue ou parle", cellClue: "Copain très proche", definition: "Personne que l’on aime bien et avec qui l’on passe du temps.", lexicalLabel: "nom masculin", example: "Youssef joue avec son ami après l’école.", direction: "across", clueRow: 3, clueCol: 5, row: 3, col: 6, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9A1466" },
      { id: "F07", answer: "EAU", clue: "Liquide transparent qui coule du robinet et que l’on boit", cellClue: "Liquide qui coule du robinet", definition: "Liquide transparent, indispensable à la vie, que l’on boit.", lexicalLabel: "nom féminin", example: "Je bois de l’eau après le sport.", direction: "across", clueRow: 6, clueCol: 6, row: 6, col: 7, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9E0003" },
      { id: "F08", answer: "SAC", clue: "Objet qui sert à ranger et transporter ses affaires", cellClue: "Pour porter ses affaires", definition: "Objet souple utilisé pour transporter ou ranger des affaires.", lexicalLabel: "nom masculin", example: "Mon cahier est dans mon sac.", direction: "across", clueRow: 1, clueCol: 3, row: 1, col: 4, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9S0048" },
      { id: "F09", answer: "STYLO", clue: "Instrument à encre qui sert à écrire", cellClue: "Pour écrire à l’encre", definition: "Instrument qui contient de l’encre et qui sert à écrire.", lexicalLabel: "nom masculin", example: "J’écris mon prénom avec un stylo bleu.", direction: "down", clueRow: 0, clueCol: 4, row: 1, col: 4, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9S3100" },
      { id: "F10", answer: "RÈGLE", clue: "Instrument droit utilisé pour tracer des lignes", cellClue: "Pour tracer des lignes", definition: "Instrument droit et gradué utilisé pour mesurer ou tracer des lignes.", lexicalLabel: "nom féminin", example: "Trace une ligne avec ta règle.", direction: "across", clueRow: 8, clueCol: 4, row: 8, col: 5, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9R1335" },
      { id: "F11", answer: "CRAIE", clue: "Petit bâton blanc ou coloré qui sert à écrire au tableau", cellClue: "On écrit au tableau avec elle", definition: "Petit bâton blanc ou coloré utilisé pour écrire sur un tableau.", lexicalLabel: "nom féminin", example: "J’écris au tableau avec une craie blanche.", direction: "down", clueRow: 0, clueCol: 6, row: 1, col: 6, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9C4764" },
    ],
  },
  {
    id: "jet-encre-mf-normal-01",
    version: 3,
    rewardVersion: 1,
    levelId: "normal",
    level: "Normal",
    cefr: "A1–A2",
    title: "Le Maroc en mots",
    theme: "Géographie, ville et culture quotidienne du Maroc",
    xp: 35,
    rows: 12,
    cols: 12,
    entries: [
      { id: "N01", answer: "MOSQUÉE", clue: "Lieu où prient les musulmans", cellClue: "Lieu de prière musulman", definition: "Lieu de culte où les musulmans se réunissent pour prier.", lexicalLabel: "nom féminin", example: "Cette mosquée possède un haut minaret.", direction: "across", clueRow: 5, clueCol: 1, row: 5, col: 2, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9M2916" },
      { id: "N02", answer: "ATLAS", clue: "Chaîne montagneuse du Maroc à la Tunisie", cellClue: "Montagnes du Maghreb", definition: "Chaîne de montagnes qui traverse le Maroc, l’Algérie et la Tunisie.", lexicalLabel: "nom propre masculin", example: "L’Atlas traverse une grande partie du Maroc.", direction: "down", clueRow: 0, clueCol: 4, row: 1, col: 4, sourceLabel: "Visit Morocco et Larousse", sourceUrl: "https://www.visitmorocco.com/fr/decouvrir-le-maroc/geographie-du-maroc" },
      { id: "N03", answer: "ARGAN", clue: "Fruit marocain dont les graines servent à produire une huile", cellClue: "Fruit d’un arbre marocain", definition: "Fruit d’un arbre marocain dont les graines servent à fabriquer une huile.", lexicalLabel: "nom masculin", example: "On utilise l’argan pour produire une huile.", direction: "across", clueRow: 9, clueCol: 6, row: 9, col: 7, sourceLabel: "Larousse", sourceUrl: "https://www.larousse.fr/dictionnaires/francais/argan/5163" },
      { id: "N04", answer: "OASIS", clue: "Lieu vert avec de l’eau dans le désert", cellClue: "Lieu vert dans le désert", definition: "Endroit fertile dans un désert grâce à la présence d’eau.", lexicalLabel: "nom féminin", example: "Une source d’eau alimente cette oasis.", direction: "down", clueRow: 6, clueCol: 4, row: 7, col: 4, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9O0005" },
      { id: "N05", answer: "TAJINE", clue: "Plat marocain cuit sous un couvercle conique", cellClue: "Plat au couvercle conique", definition: "Plat marocain qui cuit lentement sous un couvercle en forme de cône.", lexicalLabel: "nom masculin", example: "Le tajine mijote doucement pour le déjeuner.", direction: "across", clueRow: 1, clueCol: 2, row: 1, col: 3, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9T0132" },
      { id: "N06", answer: "SOUK", clue: "Marché traditionnel du Maghreb", cellClue: "Marché du Maghreb", definition: "Marché traditionnel où l’on achète et vend différents produits.", lexicalLabel: "nom masculin", example: "Le souk du quartier est animé le samedi.", direction: "down", clueRow: 2, clueCol: 6, row: 3, col: 6, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9S2256" },
      { id: "N07", answer: "THÉ", clue: "Boisson souvent servie à la menthe au Maroc", cellClue: "Boisson chaude à la menthe", definition: "Boisson chaude préparée par infusion de feuilles, souvent servie à la menthe au Maroc.", lexicalLabel: "nom masculin", example: "Ma famille sert le thé avec de la menthe.", direction: "across", clueRow: 2, clueCol: 8, row: 2, col: 9, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9T0950" },
      { id: "N08", answer: "DÉSERT", clue: "Vaste région très sèche où les pluies sont rares", cellClue: "Région où il pleut très peu", definition: "Grande étendue aride où les précipitations sont rares et la végétation peu abondante.", lexicalLabel: "nom masculin", example: "Les nuits peuvent être froides dans le désert.", direction: "down", clueRow: 0, clueCol: 11, row: 1, col: 11, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9D1854" },
      { id: "N09", answer: "MÉDINA", clue: "Partie ancienne d’une ville du Maghreb", cellClue: "Partie ancienne d’une ville", definition: "Partie ancienne d’une ville du Maghreb, avec des ruelles et souvent des remparts.", lexicalLabel: "nom féminin", example: "Nous visitons la médina à pied.", direction: "across", clueRow: 10, clueCol: 0, row: 10, col: 1, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9M1530" },
      { id: "N10", answer: "MAROC", clue: "Pays dont Rabat est la capitale", cellClue: "Pays dont Rabat est la capitale", definition: "Pays d’Afrique du Nord dont la capitale est Rabat.", lexicalLabel: "nom propre masculin", example: "Le Maroc se trouve au nord-ouest de l’Afrique.", direction: "across", clueRow: 7, clueCol: 0, row: 7, col: 1, sourceLabel: "Nations Unies", sourceUrl: "https://data.un.org/en/iso/ma.html" },
      { id: "N11", answer: "ROSE", clue: "Fleur parfumée d’un arbuste épineux", cellClue: "Fleur d’un arbuste épineux", definition: "Fleur souvent parfumée qui pousse sur un arbuste avec des épines.", lexicalLabel: "nom féminin", example: "Une rose parfume le jardin.", direction: "across", clueRow: 4, clueCol: 7, row: 4, col: 8, sourceLabel: "Office National Marocain du Tourisme", sourceUrl: "https://www.visitmorocco.com/fr/decouvrir-le-maroc/produits-du-terroir" },
      { id: "N12", answer: "HAMMAM", clue: "Bain public traditionnel avec vapeur", cellClue: "Bain traditionnel à vapeur", definition: "Bain public traditionnel, chaud et humide, où l’on se lave.", lexicalLabel: "nom masculin", example: "Le hammam du quartier ferme le lundi.", direction: "down", clueRow: 2, clueCol: 2, row: 3, col: 2, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9H0129" },
      { id: "N13", answer: "REMPART", clue: "Mur fortifié qui protège une ville", cellClue: "Mur qui protège une ville", definition: "Mur fortifié construit pour protéger une ville ou un lieu.", lexicalLabel: "nom masculin", example: "Un ancien rempart entoure une partie de la ville.", direction: "down", clueRow: 3, clueCol: 8, row: 4, col: 8, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9R1624" },
    ],
  },
  {
    id: "jet-encre-mf-difficile-01",
    version: 3,
    rewardVersion: 1,
    levelId: "difficile",
    level: "Difficile",
    cefr: "A2–B1",
    title: "Planète et citoyenneté",
    theme: "Environnement, sciences et droits",
    xp: 50,
    rows: 13,
    cols: 13,
    entries: [
      { id: "D01", answer: "CLIMAT", clue: "Conditions météo habituelles d’une région", cellClue: "Temps habituel d’une région", definition: "Ensemble des conditions météo habituelles d’une région pendant une longue période.", lexicalLabel: "nom masculin", example: "Le climat varie d’une région à l’autre.", direction: "across", clueRow: 2, clueCol: 5, row: 2, col: 6, sourceLabel: "Météo-France", sourceUrl: "https://meteofrance.com/changement-climatique/le-climat-en-france-hexagonale-et-corse" },
      { id: "D02", answer: "LÉGAL", clue: "Qui est conforme à la loi", cellClue: "Autorisé par la loi", definition: "Qui respecte la loi ou qui est autorisé par elle.", lexicalLabel: "adjectif masculin", example: "Le stationnement est légal dans cette rue.", direction: "down", clueRow: 7, clueCol: 10, row: 8, col: 10, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9L0504" },
      { id: "D03", answer: "NATURE", clue: "Monde vivant non fabriqué par les humains", cellClue: "Monde vivant et ses milieux", definition: "Ensemble des êtres vivants et des éléments qui ne sont pas fabriqués par les humains.", lexicalLabel: "nom féminin", example: "Nous protégeons la nature en réduisant nos déchets.", direction: "down", clueRow: 0, clueCol: 10, row: 1, col: 10, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9N0131" },
      { id: "D04", answer: "DÉCHET", clue: "Objet ou matière que l’on jette", cellClue: "Ce que l’on jette", definition: "Objet, matière ou substance dont on se débarrasse après usage.", lexicalLabel: "nom masculin", example: "Dépose ce déchet dans la bonne poubelle.", direction: "down", clueRow: 4, clueCol: 1, row: 5, col: 1, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9D0432" },
      { id: "D05", answer: "OZONE", clue: "Gaz de la stratosphère qui protège des rayons UV", cellClue: "Gaz qui absorbe les UV", definition: "Gaz qui, dans la stratosphère, aide à protéger la Terre des rayons ultraviolets.", lexicalLabel: "nom masculin", example: "L’ozone protège la Terre d’une partie des rayons UV.", direction: "across", clueRow: 12, clueCol: 2, row: 12, col: 3, sourceLabel: "Secrétariat de l’ozone de l’ONU", sourceUrl: "https://ozone.unep.org/20-questions-and-answers" },
      { id: "D06", answer: "OCÉAN", clue: "Immense étendue d’eau salée", cellClue: "Immense étendue d’eau salée", definition: "Très vaste étendue d’eau salée couvrant une grande partie de la Terre.", lexicalLabel: "nom masculin", example: "L’océan Atlantique borde le Maroc.", direction: "down", clueRow: 7, clueCol: 6, row: 8, col: 6, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9O0143" },
      { id: "D07", answer: "DROIT", clue: "Protection ou liberté garantie par la loi", cellClue: "Ce que garantit la loi", definition: "Possibilité ou protection reconnue à une personne par la loi.", lexicalLabel: "nom masculin", example: "Chaque enfant a le droit d’aller à l’école.", direction: "across", clueRow: 4, clueCol: 2, row: 4, col: 3, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/droit" },
      { id: "D08", answer: "DEVOIR", clue: "Obligation morale ou légale", cellClue: "Ce que l’on doit faire", definition: "Obligation morale ou légale imposée à une personne.", lexicalLabel: "nom masculin", example: "Respecter les autres est un devoir de chacun.", direction: "across", clueRow: 8, clueCol: 2, row: 8, col: 3, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/devoir" },
      { id: "D09", answer: "TRI", clue: "Action de séparer des éléments par catégories", cellClue: "Action de classer", definition: "Action de séparer des éléments en groupes selon leur type.", lexicalLabel: "nom masculin", example: "Le tri sépare le papier, le verre et le plastique.", direction: "down", clueRow: 5, clueCol: 7, row: 6, col: 7, sourceLabel: "CNRTL", sourceUrl: "https://www.cnrtl.fr/definition/tri" },
      { id: "D10", answer: "RESPECT", clue: "Attitude qui consiste à bien traiter les autres", cellClue: "Bien traiter les autres", definition: "Attitude qui consiste à traiter les autres avec attention et considération.", lexicalLabel: "nom masculin", example: "Le respect commence par l’écoute des autres.", direction: "down", clueRow: 3, clueCol: 4, row: 4, col: 4, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9R2081" },
      { id: "D11", answer: "ÉCOSYSTÈME", clue: "Ensemble d’êtres vivants et de leur milieu en interaction", cellClue: "Vie et milieu en interaction", definition: "Ensemble formé par des êtres vivants, leur milieu et leurs interactions.", lexicalLabel: "nom masculin", example: "Une forêt forme un écosystème riche.", direction: "across", clueRow: 6, clueCol: 0, row: 6, col: 1, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9E0321" },
      { id: "D12", answer: "PROPRETÉ", clue: "Absence de saleté dans un lieu", cellClue: "Absence de saleté", definition: "État d’un lieu ou d’un objet qui ne présente pas de saleté.", lexicalLabel: "nom féminin", example: "La propreté de la classe dépend de chacun.", direction: "down", clueRow: 4, clueCol: 12, row: 5, col: 12, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9P4641" },
      { id: "D13", answer: "ÉNERGIE", clue: "Capacité à produire un mouvement, de la chaleur ou un changement", cellClue: "Ce qui fait bouger ou chauffer", definition: "Capacité à produire un mouvement, de la chaleur ou un autre changement.", lexicalLabel: "nom féminin", example: "Le soleil fournit une énergie renouvelable.", direction: "across", clueRow: 10, clueCol: 5, row: 10, col: 6, sourceLabel: "Académie française", sourceUrl: "https://www.dictionnaire-academie.fr/article/A9E1519" },
    ],
  },
]);

export const MOTS_FLECHES_GRIDS = Object.freeze([
  ORIGINAL_MOTS_FLECHES_GRIDS[0],
  ...EXTRA_FACILE_GRIDS,
  ORIGINAL_MOTS_FLECHES_GRIDS[1],
  ...EXTRA_NORMAL_GRIDS,
  ORIGINAL_MOTS_FLECHES_GRIDS[2],
  ...EXTRA_DIFFICILE_GRIDS,
]);

export const MOTS_FLECHES_TOTAL_XP = MOTS_FLECHES_GRIDS.reduce((total, grid) => total + grid.xp, 0);
