const ROBERT_DEFINITION_ROOT = "https://dictionnaire.lerobert.com/definition";

// Matrice 12 × 12 validée : treize cases-indices distinctes et douze croisements.
const NORMAL_LAYOUT = Object.freeze([
  Object.freeze({ direction: "across", clueRow: 1, clueCol: 2, row: 1, col: 3 }),
  Object.freeze({ direction: "down", clueRow: 0, clueCol: 4, row: 1, col: 4 }),
  Object.freeze({ direction: "across", clueRow: 2, clueCol: 8, row: 2, col: 9 }),
  Object.freeze({ direction: "down", clueRow: 0, clueCol: 11, row: 1, col: 11 }),
  Object.freeze({ direction: "down", clueRow: 2, clueCol: 6, row: 3, col: 6 }),
  Object.freeze({ direction: "across", clueRow: 4, clueCol: 7, row: 4, col: 8 }),
  Object.freeze({ direction: "down", clueRow: 3, clueCol: 8, row: 4, col: 8 }),
  Object.freeze({ direction: "across", clueRow: 5, clueCol: 1, row: 5, col: 2 }),
  Object.freeze({ direction: "across", clueRow: 7, clueCol: 0, row: 7, col: 1 }),
  Object.freeze({ direction: "down", clueRow: 6, clueCol: 4, row: 7, col: 4 }),
  Object.freeze({ direction: "across", clueRow: 9, clueCol: 6, row: 9, col: 7 }),
  Object.freeze({ direction: "across", clueRow: 10, clueCol: 0, row: 10, col: 1 }),
  Object.freeze({ direction: "down", clueRow: 2, clueCol: 2, row: 3, col: 2 }),
]);

function buildEntries(prefix, items) {
  if (items.length !== NORMAL_LAYOUT.length) {
    throw new Error(`${prefix} doit contenir exactement ${NORMAL_LAYOUT.length} mots.`);
  }

  return Object.freeze(items.map((item, index) => {
    const {
      sourceSlug,
      sourceLabel = "Le Robert",
      sourceUrl,
      ...content
    } = item;
    const resolvedSourceUrl = sourceUrl || `${ROBERT_DEFINITION_ROOT}/${sourceSlug}`;
    if (!resolvedSourceUrl.startsWith("https://")) {
      throw new Error(`${prefix}-${index + 1} doit posséder une source HTTPS.`);
    }

    return Object.freeze({
      id: `${prefix}-${String(index + 1).padStart(2, "0")}`,
      ...content,
      ...NORMAL_LAYOUT[index],
      sourceLabel,
      sourceUrl: resolvedSourceUrl,
    });
  }));
}

function buildNormalGrid({ id, entryPrefix, title, theme, items }) {
  return Object.freeze({
    id,
    version: 1,
    rewardVersion: 1,
    levelId: "normal",
    level: "Normal",
    cefr: "A1–A2",
    title,
    theme,
    xp: 35,
    rows: 12,
    cols: 12,
    entries: buildEntries(entryPrefix, items),
  });
}

export const EXTRA_NORMAL_GRIDS = Object.freeze([
  buildNormalGrid({
    id: "jet-encre-mf-normal-02",
    entryPrefix: "N02",
    title: "Au marché et en cuisine",
    theme: "Produits, repas et gestes culinaires dans la vie quotidienne au Maroc",
    items: [
      {
        answer: "AMANDE",
        clue: "Fruit à coque dont on mange la graine",
        cellClue: "Graine dans une coque",
        definition: "Graine comestible, douce ou légèrement amère, cachée dans une coque dure.",
        lexicalLabel: "nom féminin",
        example: "On ajoute une amande grillée sur chaque gâteau.",
        sourceSlug: "amande",
      },
      {
        answer: "MIXER",
        clue: "Réduire ou mélanger des aliments avec un appareil électrique",
        cellClue: "Réduire des aliments en purée",
        definition: "Réduire des aliments en petits morceaux ou les mélanger avec un appareil électrique.",
        lexicalLabel: "verbe à l’infinitif",
        example: "Nous allons mixer les légumes pour préparer le velouté.",
        sourceSlug: "mixer",
      },
      {
        answer: "BLÉ",
        clue: "Céréale utilisée pour fabriquer de la farine",
        cellClue: "Céréale du pain",
        definition: "Céréale cultivée pour ses grains, principalement transformés en farine.",
        lexicalLabel: "nom masculin",
        example: "Le blé mûrit dans les champs avant la récolte.",
        sourceSlug: "ble",
      },
      {
        answer: "LÉGUME",
        clue: "Plante cultivée que l’on mange cuite ou crue",
        cellClue: "Plante que l’on cuisine",
        definition: "Plante cultivée dont une partie se mange, crue ou après cuisson.",
        lexicalLabel: "nom masculin",
        example: "La carotte est un légume souvent utilisé dans le couscous.",
        sourceSlug: "legume",
      },
      {
        answer: "LAIT",
        clue: "Liquide blanc produit par certains animaux",
        cellClue: "Boisson blanche",
        definition: "Liquide blanc et nourrissant produit par les femelles de certains mammifères.",
        lexicalLabel: "nom masculin",
        example: "Le lait chaud accompagne parfois le petit déjeuner.",
        sourceSlug: "lait",
      },
      {
        answer: "MENU",
        clue: "Liste des plats proposés pour un repas",
        cellClue: "Liste des plats d’un repas",
        definition: "Liste organisée des plats et des boissons proposés au cours d’un repas.",
        lexicalLabel: "nom masculin",
        example: "Le menu du jour présente une salade et un plat chaud.",
        sourceSlug: "menu",
      },
      {
        answer: "MERGUEZ",
        clue: "Fine saucisse rouge généralement bien épicée",
        cellClue: "Saucisse épicée",
        definition: "Fine saucisse rouge préparée avec de la viande et plusieurs épices.",
        lexicalLabel: "nom féminin",
        example: "La merguez cuit doucement sur le gril familial.",
        sourceSlug: "merguez",
      },
      {
        answer: "TARTINE",
        clue: "Tranche de pain recouverte d’un aliment",
        cellClue: "Tranche de pain garnie",
        definition: "Tranche de pain sur laquelle on étale du beurre, du miel ou une autre garniture.",
        lexicalLabel: "nom féminin",
        example: "Je prépare une tartine au miel pour le goûter.",
        sourceSlug: "tartine",
      },
      {
        answer: "SOUPE",
        clue: "Préparation liquide servie chaude ou froide",
        cellClue: "Plat chaud et liquide",
        definition: "Préparation liquide faite avec des légumes, des céréales ou d’autres aliments.",
        lexicalLabel: "nom féminin",
        example: "Une soupe de légumes réchauffe la famille le soir.",
        sourceSlug: "soupe",
      },
      {
        answer: "PÂTES",
        clue: "Aliments préparés avec de la farine et de l’eau",
        cellClue: "Penne et nouilles",
        definition: "Aliments obtenus avec une préparation de farine et d’eau, puis découpés en formes variées.",
        lexicalLabel: "nom féminin pluriel",
        example: "Les pâtes cuisent dans une grande casserole d’eau.",
        sourceSlug: "pate",
      },
      {
        answer: "MELON",
        clue: "Gros fruit rond à la chair très juteuse",
        cellClue: "Fruit d’été",
        definition: "Gros fruit rond à peau épaisse, dont la chair sucrée contient beaucoup d’eau.",
        lexicalLabel: "nom masculin",
        example: "Le melon frais est partagé après le déjeuner.",
        sourceSlug: "melon",
      },
      {
        answer: "PIMENT",
        clue: "Petit fruit qui donne un goût très fort aux plats",
        cellClue: "Petit fruit très piquant",
        definition: "Petit fruit rouge, vert ou jaune qui peut donner une saveur très forte aux aliments.",
        lexicalLabel: "nom masculin",
        example: "Un peu de piment suffit pour relever la sauce.",
        sourceSlug: "piment",
      },
      {
        answer: "CITRON",
        clue: "Fruit jaune dont le jus a un goût très acide",
        cellClue: "Agrume acide",
        definition: "Fruit jaune de forme ovale, riche en jus et reconnaissable à son goût acide.",
        lexicalLabel: "nom masculin",
        example: "On presse un citron sur la salade marocaine.",
        sourceSlug: "citron",
      },
    ],
  }),
  buildNormalGrid({
    id: "jet-encre-mf-normal-03",
    entryPrefix: "N03",
    title: "Du village au littoral",
    theme: "Déplacements et paysages marocains, de l’intérieur du pays à la côte",
    items: [
      {
        answer: "CHEMIN",
        clue: "Petite voie qui permet d’aller d’un lieu à un autre",
        cellClue: "Petite voie entre deux lieux",
        definition: "Voie généralement étroite aménagée pour marcher ou circuler entre deux lieux.",
        lexicalLabel: "nom masculin",
        example: "Le chemin traverse les oliviers près du village.",
        sourceSlug: "chemin",
      },
      {
        answer: "HÔTEL",
        clue: "Établissement où les voyageurs peuvent dormir",
        cellClue: "Lieu où les voyageurs dorment",
        definition: "Établissement qui propose des chambres et des services aux voyageurs.",
        lexicalLabel: "nom masculin",
        example: "Notre hôtel se trouve près de la gare de Tanger.",
        sourceSlug: "hotel",
      },
      {
        answer: "SOL",
        clue: "Surface de la terre sur laquelle on marche",
        cellClue: "Surface où l’on marche",
        definition: "Partie supérieure de la terre sur laquelle on marche et où poussent les plantes.",
        lexicalLabel: "nom masculin",
        example: "Le sol devient rouge sur cette piste du Sud.",
        sourceSlug: "sol",
      },
      {
        answer: "PLAINE",
        clue: "Grande étendue de terre presque plate",
        cellClue: "Grande étendue de terre plate",
        definition: "Grande étendue de terre peu élevée, avec de faibles différences de hauteur.",
        lexicalLabel: "nom féminin",
        example: "Une vaste plaine agricole entoure la ville de Meknès.",
        sourceSlug: "plaine",
      },
      {
        answer: "RIAD",
        clue: "Maison marocaine organisée autour d’une cour intérieure",
        cellClue: "Maison avec cour",
        definition: "Maison traditionnelle marocaine construite autour d’une cour ou d’un jardin intérieur.",
        lexicalLabel: "nom masculin",
        example: "Le riad possède une cour calme avec une fontaine.",
        sourceSlug: "riad",
      },
      {
        answer: "TAXI",
        clue: "Voiture avec chauffeur que l’on paie pour un trajet",
        cellClue: "Avec chauffeur",
        definition: "Voiture conduite par un professionnel qui transporte des passagers contre paiement.",
        lexicalLabel: "nom masculin",
        example: "Nous prenons un taxi pour rejoindre la médina.",
        sourceSlug: "taxi",
      },
      {
        answer: "TERRAIN",
        clue: "Espace de terre délimité pour un usage précis",
        cellClue: "Parcelle de terre",
        definition: "Espace de terre défini par des limites et destiné à une activité particulière.",
        lexicalLabel: "nom masculin",
        example: "Le terrain près du douar sert aux jeux des enfants.",
        sourceSlug: "terrain",
      },
      {
        answer: "VILLAGE",
        clue: "Petit ensemble de maisons situé à la campagne",
        cellClue: "Petit bourg",
        definition: "Petite agglomération rurale composée de maisons et de quelques services.",
        lexicalLabel: "nom masculin",
        example: "Le village se réunit chaque semaine autour du marché.",
        sourceSlug: "village",
      },
      {
        answer: "AGAVE",
        clue: "Grande plante aux feuilles épaisses terminées en pointe",
        cellClue: "Plante aux feuilles épaisses",
        definition: "Grande plante des régions chaudes portant de longues feuilles épaisses et pointues.",
        lexicalLabel: "nom masculin",
        example: "Un agave pousse au bord de la route côtière.",
        sourceSlug: "agave",
      },
      {
        answer: "VAGUE",
        clue: "Mouvement de l’eau qui se forme à la surface de la mer",
        cellClue: "Mouvement de la mer",
        definition: "Masse d’eau qui monte, avance puis se brise à la surface de la mer.",
        lexicalLabel: "nom féminin",
        example: "Une vague atteint doucement la plage d’Essaouira.",
        sourceSlug: "vague",
      },
      {
        answer: "PISTE",
        clue: "Voie souvent non goudronnée en dehors des villes",
        cellClue: "Voie non goudronnée",
        definition: "Voie aménagée de façon simple pour circuler dans une zone rurale ou naturelle.",
        lexicalLabel: "nom féminin",
        example: "La piste mène vers un petit village de montagne.",
        sourceSlug: "piste",
      },
      {
        answer: "FLEUVE",
        clue: "Grand cours d’eau qui se jette dans la mer",
        cellClue: "Cours d’eau allant à la mer",
        definition: "Grand cours d’eau qui termine son trajet dans une mer ou dans un océan.",
        lexicalLabel: "nom masculin",
        example: "Le fleuve Sebou traverse une région agricole importante.",
        sourceSlug: "fleuve",
      },
      {
        answer: "RIVAGE",
        clue: "Bord d’une mer, d’un lac ou d’un grand cours d’eau",
        cellClue: "Bord d’une mer ou d’un lac",
        definition: "Zone de terre située au contact d’une grande étendue d’eau.",
        lexicalLabel: "nom masculin",
        example: "Les pêcheurs reviennent vers le rivage avant la nuit.",
        sourceSlug: "rivage",
      },
    ],
  }),
  buildNormalGrid({
    id: "jet-encre-mf-normal-04",
    entryPrefix: "N04",
    title: "Les artisans de la médina",
    theme: "Matières, gestes et métiers de l’artisanat marocain",
    items: [
      {
        answer: "ÉTOFFE",
        clue: "Matière souple fabriquée avec des fils et utilisée pour coudre",
        cellClue: "Tissu à coudre",
        definition: "Matière textile souple obtenue par l’assemblage de fils et destinée à la couture.",
        lexicalLabel: "nom féminin",
        example: "Cette étoffe colorée servira à confectionner un coussin.",
        sourceSlug: "etoffe",
      },
      {
        answer: "TAPIS",
        clue: "Pièce textile épaisse que l’on pose sur le sol",
        cellClue: "Pièce textile posée au sol",
        definition: "Pièce textile décorative ou protectrice que l’on étend sur le sol.",
        lexicalLabel: "nom masculin",
        example: "L’artisane termine un tapis aux motifs géométriques.",
        sourceSlug: "tapis",
      },
      {
        answer: "FIL",
        clue: "Brin long et fin utilisé pour coudre ou fabriquer un tissu",
        cellClue: "Brin utilisé pour coudre",
        definition: "Brin très fin et allongé que l’on emploie pour coudre, broder ou fabriquer un textile.",
        lexicalLabel: "nom masculin",
        example: "Le fil rouge passe dans le chas de l’aiguille.",
        sourceSlug: "fil",
      },
      {
        answer: "CLOUER",
        clue: "Fixer un objet avec une pointe métallique et un marteau",
        cellClue: "Fixer avec des pointes",
        definition: "Fixer solidement un objet en enfonçant une ou plusieurs pointes métalliques.",
        lexicalLabel: "verbe à l’infinitif",
        example: "L’artisan va clouer la petite planche de bois.",
        sourceSlug: "clouer",
      },
      {
        answer: "ÉTAL",
        clue: "Table où un vendeur présente ses produits au marché",
        cellClue: "Table d’un vendeur",
        definition: "Table ou installation sur laquelle un marchand expose les produits qu’il vend.",
        lexicalLabel: "nom masculin",
        example: "Des paniers en osier remplissent l’étal du marchand.",
        sourceSlug: "etal",
      },
      {
        answer: "PEAU",
        clue: "Enveloppe naturelle qui recouvre le corps d’un animal",
        cellClue: "Enveloppe du corps",
        definition: "Enveloppe naturelle qui protège le corps des humains et des animaux.",
        lexicalLabel: "nom féminin",
        example: "Le cuir est obtenu après un travail précis de la peau.",
        sourceSlug: "peau",
      },
      {
        answer: "PEINTRE",
        clue: "Professionnel qui applique de la couleur sur un mur ou un objet",
        cellClue: "Artisan qui colore les murs",
        definition: "Personne dont le métier consiste à appliquer des couleurs sur une surface.",
        lexicalLabel: "nom masculin ou féminin",
        example: "La peintre décore le panneau avec un motif bleu.",
        sourceSlug: "peintre",
      },
      {
        answer: "TISSAGE",
        clue: "Action d’entrelacer des fils pour former un textile",
        cellClue: "Croiser des fils",
        definition: "Action d’entrecroiser des fils tendus afin de fabriquer une matière textile.",
        lexicalLabel: "nom masculin",
        example: "Le tissage de ce motif demande beaucoup de patience.",
        sourceSlug: "tissage",
      },
      {
        answer: "TENUE",
        clue: "Ensemble de vêtements portés au même moment",
        cellClue: "Habits portés",
        definition: "Ensemble des vêtements choisis et portés par une personne à une occasion donnée.",
        lexicalLabel: "nom féminin",
        example: "Sa tenue de fête comporte une ceinture brodée.",
        sourceSlug: "tenue",
      },
      {
        answer: "USINE",
        clue: "Grand bâtiment où des produits sont fabriqués avec des machines",
        cellClue: "Lieu où l’on fabrique en série",
        definition: "Grand établissement équipé de machines où l’on fabrique des produits en série.",
        lexicalLabel: "nom féminin",
        example: "Cette usine transforme la laine avant son transport.",
        sourceSlug: "usine",
      },
      {
        answer: "TRAME",
        clue: "Ensemble des fils qui passent en travers dans un tissu",
        cellClue: "Fils croisés dans un tissu",
        definition: "Ensemble de fils transversaux entrecroisés avec les fils tendus d’un textile.",
        lexicalLabel: "nom féminin",
        example: "La trame serrée rend ce textile plus solide.",
        sourceSlug: "trame",
      },
      {
        answer: "BONNET",
        clue: "Vêtement souple qui couvre la tête",
        cellClue: "Vêtement porté sur la tête",
        definition: "Vêtement sans bord, généralement souple et chaud, que l’on porte sur la tête.",
        lexicalLabel: "nom masculin",
        example: "Le bonnet en laine a été fabriqué à la main.",
        sourceSlug: "bonnet",
      },
      {
        answer: "POTIER",
        clue: "Artisan qui façonne des objets avec de l’argile",
        cellClue: "Artisan qui travaille l’argile",
        definition: "Artisan qui modèle puis fait cuire l’argile pour créer des objets utiles ou décoratifs.",
        lexicalLabel: "nom masculin",
        example: "Le potier tourne un grand plat dans son atelier.",
        sourceSlug: "potier",
      },
    ],
  }),
  buildNormalGrid({
    id: "jet-encre-mf-normal-05",
    entryPrefix: "N05",
    title: "Musiques, fêtes et habits",
    theme: "Expressions artistiques et traditions festives du Maroc",
    items: [
      {
        answer: "GNAOUA",
        clue: "Genre musical et spirituel marocain accompagné de percussions",
        cellClue: "Musique rituelle marocaine",
        definition: "Tradition musicale et spirituelle marocaine mêlant chants, rythmes et instruments.",
        lexicalLabel: "nom masculin invariable",
        example: "Le gnaoua associe le chant, les crotales et le guembri.",
        sourceLabel: "UNESCO",
        sourceUrl: "https://ich.unesco.org/fr/RL/le-gnawa-01170",
      },
      {
        answer: "NOUBA",
        clue: "Suite de chants et de morceaux de la musique andalouse",
        cellClue: "Musique andalouse",
        definition: "Suite organisée de pièces vocales et instrumentales issue de la tradition andalouse.",
        lexicalLabel: "nom féminin",
        example: "L’orchestre interprète une nouba lors du concert.",
        sourceSlug: "nouba",
      },
      {
        answer: "SON",
        clue: "Ce que l’oreille perçoit lorsqu’un objet vibre",
        cellClue: "Ce qu’on entend",
        definition: "Ce que l’oreille perçoit lorsqu’une vibration se propage dans l’air ou dans une matière.",
        lexicalLabel: "nom masculin",
        example: "Le son du tambour annonce le début du spectacle.",
        sourceSlug: "son",
      },
      {
        answer: "ENCENS",
        clue: "Matière parfumée que l’on fait brûler",
        cellClue: "Matière qui parfume en brûlant",
        definition: "Matière aromatique qui dégage une fumée odorante lorsqu’elle brûle lentement.",
        lexicalLabel: "nom masculin",
        example: "Un peu d’encens parfume la pièce avant la cérémonie.",
        sourceSlug: "encens",
      },
      {
        answer: "FÊTE",
        clue: "Moment joyeux partagé pour célébrer un événement",
        cellClue: "Moment de joie",
        definition: "Moment collectif organisé pour célébrer un événement dans une atmosphère joyeuse.",
        lexicalLabel: "nom féminin",
        example: "Toute la famille se réunit pour la fête du village.",
        sourceSlug: "fete",
      },
      {
        answer: "CAPE",
        clue: "Vêtement sans manches posé sur les épaules",
        cellClue: "Sans manches",
        definition: "Vêtement ample et sans manches qui couvre les épaules et une partie du corps.",
        lexicalLabel: "nom féminin",
        example: "La cape brodée complète le costume de scène.",
        sourceSlug: "cape",
      },
      {
        answer: "CRAVATE",
        clue: "Bande de tissu nouée autour du cou",
        cellClue: "Accessoire noué au cou",
        definition: "Longue bande de tissu portée autour du cou et nouée sur le devant d’une chemise.",
        lexicalLabel: "nom féminin",
        example: "Il choisit une cravate bleue pour la cérémonie.",
        sourceSlug: "cravate",
      },
      {
        answer: "CHANTER",
        clue: "Faire entendre une mélodie avec sa voix",
        cellClue: "Faire entendre une mélodie",
        definition: "Produire avec sa voix une suite de notes formant une mélodie.",
        lexicalLabel: "verbe à l’infinitif",
        example: "Les élèves vont chanter ensemble devant les familles.",
        sourceSlug: "chanter",
      },
      {
        answer: "PERLE",
        clue: "Petite boule brillante utilisée pour fabriquer un bijou",
        cellClue: "Petite boule pour un bijou",
        definition: "Petite boule dure et brillante, naturelle ou fabriquée, utilisée en bijouterie.",
        lexicalLabel: "nom féminin",
        example: "L’artisane ajoute une perle verte au collier.",
        sourceSlug: "perle",
      },
      {
        answer: "LAINE",
        clue: "Fibre douce provenant notamment du mouton",
        cellClue: "Fibre douce du mouton",
        definition: "Fibre textile douce et chaude obtenue à partir du pelage de certains animaux.",
        lexicalLabel: "nom féminin",
        example: "La laine est teinte avant la fabrication du vêtement.",
        sourceSlug: "laine",
      },
      {
        answer: "STYLE",
        clue: "Manière particulière de créer ou de s’exprimer",
        cellClue: "Manière propre à un artiste",
        definition: "Manière personnelle et reconnaissable de créer, de s’habiller ou de s’exprimer.",
        lexicalLabel: "nom masculin",
        example: "Le groupe possède un style musical facile à reconnaître.",
        sourceSlug: "style",
      },
      {
        answer: "SONNER",
        clue: "Produire un bruit clair avec une cloche ou un instrument",
        cellClue: "Produire un bruit clair",
        definition: "Produire ou faire entendre un bruit clair, souvent avec une cloche ou un instrument.",
        lexicalLabel: "verbe à l’infinitif",
        example: "Le musicien fait sonner les crotales en rythme.",
        sourceSlug: "sonner",
      },
      {
        answer: "SACHET",
        clue: "Petit contenant souple fermé sur les côtés",
        cellClue: "Petit sac",
        definition: "Petit contenant léger et souple utilisé pour conserver ou transporter une petite quantité.",
        lexicalLabel: "nom masculin",
        example: "Le marchand remplit un sachet de pétales parfumés.",
        sourceSlug: "sachet",
      },
    ],
  }),
  buildNormalGrid({
    id: "jet-encre-mf-normal-06",
    entryPrefix: "N06",
    title: "Notre classe au Maroc",
    theme: "École, entraide et activités de la vie scolaire marocaine",
    items: [
      {
        answer: "CRAYON",
        clue: "Instrument à mine utilisé pour écrire ou dessiner",
        cellClue: "Sert à écrire ou dessiner",
        definition: "Petit instrument allongé dont la mine laisse une trace sur le papier.",
        lexicalLabel: "nom masculin",
        example: "Salma utilise un crayon gris pour faire son schéma.",
        sourceSlug: "crayon",
      },
      {
        answer: "RADIO",
        clue: "Moyen de communication que l’on écoute",
        cellClue: "Média que l’on écoute",
        definition: "Moyen de communication qui diffuse des voix, de la musique et des informations par les ondes.",
        lexicalLabel: "nom féminin",
        example: "La radio scolaire présente le projet de la classe.",
        sourceSlug: "radio",
      },
      {
        answer: "OUI",
        clue: "Mot utilisé pour accepter ou donner son accord",
        cellClue: "Mot pour accepter",
        definition: "Mot employé pour accepter une proposition, confirmer une réponse ou donner son accord.",
        lexicalLabel: "adverbe",
        example: "Nora répond oui quand le groupe lui propose de participer.",
        sourceSlug: "oui",
      },
      {
        answer: "DICTÉE",
        clue: "Exercice où l’élève écrit un texte entendu",
        cellClue: "Texte entendu que l’on écrit",
        definition: "Exercice scolaire dans lequel on écrit correctement un texte lu à voix haute.",
        lexicalLabel: "nom féminin",
        example: "La dictée de ce matin contient cinq phrases courtes.",
        sourceSlug: "dictee",
      },
      {
        answer: "QUIZ",
        clue: "Jeu composé de plusieurs questions courtes",
        cellClue: "Jeu de questions",
        definition: "Jeu ou exercice formé de questions courtes pour vérifier ou enrichir ses connaissances.",
        lexicalLabel: "nom masculin",
        example: "Le quiz permet de revoir le vocabulaire de la semaine.",
        sourceSlug: "quiz",
      },
      {
        answer: "TEST",
        clue: "Petite épreuve utilisée pour vérifier des connaissances",
        cellClue: "Petite épreuve de contrôle",
        definition: "Épreuve courte qui sert à vérifier une connaissance, une capacité ou un résultat.",
        lexicalLabel: "nom masculin",
        example: "Le test dure dix minutes et comporte quatre questions.",
        sourceSlug: "test",
      },
      {
        answer: "TRAVAIL",
        clue: "Activité qui demande un effort pour atteindre un résultat",
        cellClue: "Activité demandant un effort",
        definition: "Activité organisée qui demande du temps et des efforts pour obtenir un résultat.",
        lexicalLabel: "nom masculin",
        example: "Le travail en groupe commence après la récréation.",
        sourceSlug: "travail",
      },
      {
        answer: "ÉCOLIER",
        clue: "Enfant qui apprend dans une classe primaire",
        cellClue: "Jeune élève",
        definition: "Enfant qui fréquente un établissement d’enseignement primaire.",
        lexicalLabel: "nom masculin",
        example: "Chaque écolier prépare son cahier avant la leçon.",
        sourceSlug: "ecolier",
      },
      {
        answer: "FILLE",
        clue: "Enfant ou jeune personne de sexe féminin",
        cellClue: "Féminin de « garçon »",
        definition: "Enfant ou jeune personne de sexe féminin, par opposition à un garçon.",
        lexicalLabel: "nom féminin",
        example: "La fille présente le résultat au reste de la classe.",
        sourceSlug: "fille",
      },
      {
        answer: "LOCAL",
        clue: "Salle ou espace réservé à une activité précise",
        cellClue: "Salle réservée à une activité",
        definition: "Salle ou partie d’un bâtiment destinée à une activité ou à un groupe précis.",
        lexicalLabel: "nom masculin",
        example: "Le club de lecture range ses livres dans un local calme.",
        sourceSlug: "local",
      },
      {
        answer: "BILLE",
        clue: "Petite boule dure utilisée dans un jeu d’enfants",
        cellClue: "Petite boule pour jouer",
        definition: "Petite boule dure, souvent en verre, que les enfants utilisent dans différents jeux.",
        lexicalLabel: "nom féminin",
        example: "Une bille bleue roule au milieu de la cour.",
        sourceSlug: "bille",
      },
      {
        answer: "ENFANT",
        clue: "Jeune personne qui n’a pas encore atteint l’adolescence",
        cellClue: "Garçon ou fille encore jeune",
        definition: "Jeune personne encore dans les premières années de sa vie et de son développement.",
        lexicalLabel: "nom masculin ou féminin",
        example: "Chaque enfant a le droit d’apprendre dans de bonnes conditions.",
        sourceSlug: "enfant",
      },
      {
        answer: "POÉSIE",
        clue: "Art d’exprimer des émotions avec le rythme et les mots",
        cellClue: "Art qui joue avec les mots",
        definition: "Art du langage qui joue avec les sons, le rythme et les images pour exprimer des émotions.",
        lexicalLabel: "nom féminin",
        example: "La poésie choisie évoque la mer et les villes du Maroc.",
        sourceSlug: "poesie",
      },
    ],
  }),
]);
